### ISSUE TITLE
Proxy environment variables acknowledged & ignored - 3 problem in Cobbler 2.6.5

### ISSUE THREAD

**Issue by Ed-0x1b** [cobbler/cobbler#1286]
I was testing an upgade to Cobbler 2.6.5, but ran into some issues and I need to know if I should file one overall bug, or break out the individual problems outlined below? The system is a Fedora 20 that is up to date, Python v.2.7.5 from updates, and Cobbler 2.6.5 pulled from http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/Fedora_20/ on a 10.0.0 network behind a proxy(squid). SELinux is disabled.

I have cobblerd, koan and cobbler-web installed and running, imported a Fedora 20 DVD via mounted iso without problem. The problem is that the following cobbler commands apear to be un aware (acknowledge & ignore) of the environment settings for accessing a proxy. Using the commands (curl reposync yum dnf) outside of Cobbler all work as expected and traverse the proxy without problems. Cobbler is the only application we use that fails to recognize the proxy. The problems are:
1) cobbler get-loaders
2) cobbler signature update
3) cobbler reposync

The error reports are:
1) cobbler get-loaders
task started: 2014-10-04_141545_get_loaders
task started (id=Download Bootloader Content, time=Sat Oct  4 14:15:45 2014)
downloading http://www.cobblerd.org/loaders/README to /var/lib/cobbler/loaders/README
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] curl#7 - "Failed to connect to 199.27.79.133: Network is unreachable"
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 749, in dlcontent
    return grabber.run(force)
   File "/usr/lib/python2.7/site-packages/cobbler/action_dlcontent.py", line 83, in run
    urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 735, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1176, in urlgrab
    return _run_callback(opts.failfunc, opts)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1030, in _run_callback
    return cb(obj)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1024, in _do_raise
    raise obj.exception

!!! TASK FAILED !!!

2) cobbler signature update
task started: 2014-10-04_141652_sigupdate
task started (id=Updating Signatures, time=Sat Oct  4 14:16:52 2014)
Exception occured: <class 'urllib2.URLError'>
Exception value: <urlopen error [Errno 101] Network is unreachable>
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 599, in signature_update
    response = urllib2.urlopen(self.settings().signature_url)
   File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
   File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
   File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
   File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
   File "/usr/lib64/python2.7/urllib2.py", line 1216, in http_open
    return self.do_open(httplib.HTTPConnection, req)
   File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
    raise URLError(err)

!!! TASK FAILED !!!

3) cobbler reposync - for example the F20-Cobbler26 repo:
Name                           : F20-Cobbler26
Apt Components (apt only)      : []
Apt Dist Names (apt only)      : []
Arch                           : x86_64
Breed                          : yum
Comment                        : 
Createrepo Flags               : <<inherit>>
Environment Variables          : {'http_proxy': 'http://10.0.0.100:3128'}
Keep Updated                   : True
Mirror                         : http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/Fedora_20/
Mirror locally                 : True
Owners                         : ['admin']
Priority                       : 60
RPM List                       : []
Yum Options                    : {}

cobbler reposync --only=F20-Cobbler26

task started: 2014-10-04_141359_reposync
task started (id=Reposync, time=Sat Oct  4 14:13:59 2014)
hello, reposync
run, reposync, run!
setting repo environment: http_proxy=http://10.0.0.100:3128
creating: /var/www/cobbler/repo_mirror/F20-Cobbler26/.origin/F20-Cobbler26.repo
running: /usr/bin/reposync -l -n --config=/var/www/cobbler/repo_mirror/F20-Cobbler26/.origin/F20-Cobbler26.repo --repoid=F20-Cobbler26 --download_path=/var/www/cobbler/repo_mirror -a x86_64
received on stdout: 
received on stderr: Traceback (most recent call last):
  File "/usr/bin/reposync", line 326, in <module>
    main()
  File "/usr/bin/reposync", line 165, in main
    my.doRepoSetup()
  File "/usr/lib/python2.7/site-packages/yum/**init**.py", line 689, in doRepoSetup
    return self._getRepos(thisrepo, True)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 729, in _getRepos
    self._repos.doSetup(thisrepo)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 157, in doSetup
    self.retrieveAllMD()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 88, in retrieveAllMD
    dl = repo._async and repo._commonLoadRepoXML(repo)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1460, in _commonLoadRepoXML
    result = self._getFileRepoXML(local, text)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1234, in _getFileRepoXML
    size=102400) # setting max size as 100K
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1014, in _getFile
    result = self.grab.urlgrab(misc.to_utf8(relative), local,
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 698, in <lambda>
    grab = property(lambda self: self._getgrab())
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 693, in _getgrab
    self._setupGrab()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 631, in _setupGrab
    urls = self.urls
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 875, in <lambda>
    urls = property(fget=lambda self: self._geturls(),
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 872, in _geturls
    self._baseurlSetup()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 818, in _baseurlSetup
    mirrorurls.extend(list(self.metalink_data.urls()))
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 915, in <lambda>
    metalink_data = property(fget=lambda self: self._getMetalink(),
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 894, in _getMetalink
    raise Errors.RepoError(msg, repo=self)
yum.Errors.RepoError: Cannot retrieve metalink for repository: fedora/20/x86_64. Please verify its path and try again
....clip....

**Comment by brianjmurrell** [comment]
This only indirectly addresses @Ed-0x1b's problem.  It does introduce a new setting: ```proxy_url_ext``` to configure a proxy but ```cobblerd``` is still not honouring any ```http[s]_proxy``` environment variables.  I see that the patch is removing the honouring of the upper case ```HTTP_PROXY``` for the ```ContentDownloader``` class.  For what it's worth, I've always used lower case ```http_proxy``` and perhaps so was @Ed-0x1b.  Unfortunately ```HTTPS_PROXY``` and ```https_proxy``` are a bit more ambiguous and I have seen both used so probably both should be supported.  :-(

In any case, these environment variables are a widespread, de facto standard.  People who have proxy environments go to the pains of configuring their systems to set those variables properly into the environments of the processes running on the machines.  To have to additionally sprinkle them around into application specific configurations is a pain, but more importantly, error-prone.

I'm not saying get rid of ```proxy_url_ext``` now that it's there, but if it's not set and the ```{http[s]_proxy,HTTPS_PROXY}``` environment variables are, they should be honoured.

Should probably also be honouring ```no_proxy``` but that is probably secondary to this main issue.

**Comment by Ed-0x1b** [comment]
+1 for Brian's position - keep proxy_url_ext and honor env.

I have noticed this problem with proxies across several projects and have begun thinking of it as "the missing unit tests". I now think that many of the problems have to do with the embedded use of curl (python and nodejs projects in particular) and curl's default no-follow behavior for 3xx redirects. I have had some success in adding -L and proxy configuration to /etc/curlrc - although after a quick look, I can no longer find the ref of that global config file in the man document.

I have both upper and lower case and both http and https environment variables set and still sometimes a local mrepo mirror is the only way to mirror a repo into cobbler.
