### ISSUE TITLE
2.6.6 Fails to start without proxy_url_ext (and _int?) defined in settings

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#1311]
Updated to 2.6.6 via yum.  New settings file goes to settings.rpmnew.  Without updating settings, cobblerd fails to start with:
~~~~
Starting cobbler daemon: Traceback (most recent call last):
  File "/usr/bin/cobblerd", line 77, in main
    api = cobbler_api.BootAPI(is_cobblerd=True)
  File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 135, in __init__
    self.deserialize()
  File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 969, in deserialize
    return self._config.deserialize()
  File "/usr/lib/python2.6/site-packages/cobbler/config.py", line 266, in deserialize
    raise CX("serializer: error loading collection %s. Check /etc/cobbler/modules.conf" % item.collection_type())
CX: 'serializer: error loading collection repo. Check /etc/cobbler/modules.conf'
~~~~
Editing config.py to keep the original exception shows:
~~~~
  File "/usr/lib/python2.6/site-packages/cobbler/settings.py", line 271, in __getattr__
    raise AttributeError, name
AttributeError: proxy_url_ext
~~~~
Adding the entries to settings fixes.  Is there a way for the module to have a default value so we don't get an exception on load?

**Comment by jmaas** [comment]
2.6.7 has been released which fixes this issue.

**Comment by robinbowes** [comment]
Did this get pushed? I don't see 2.6.7 in Fedora 21?

**Comment by jmaas** [comment]
@opoplawski ?

**Comment by opoplawski** [comment]
It's in updates-testing waiting for positive feedback: https://admin.fedoraproject.org/updates/FEDORA-2015-0039/cobbler-2.6.7-1.fc21

**Comment by robinbowes** [comment]
Ah, OK. I've grabbed it from there, thanks.
