### ISSUE TITLE
cobbler wont work on ubuntu

### ISSUE THREAD

**Issue by gnugplman** [cobbler/cobbler#1511]
Installed from repo, fresh ubuntu 14.04 instalation, and i get this error, for anything i try.
httpd does not appear to be running and proxying cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cobbler/cli.py", line 252, in check_setup
    s.ping()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for 10.1.5.104:80/cobbler_api: 503 Service Unavailable>

**Comment by pascal-chenevas** [comment]
Hi !

which version of cobbler do you use?
can you please give the result of the following commands ?

```bash
# systemctl status httpd | grep "Active:"
# systemctl status cobblerd | grep "Active:"
# getenforce
```
Thank you!
