### ISSUE TITLE
cobbler 2.6.9 ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by pascal-chenevas** [cobbler/cobbler#1513]
Hi,

I'am facing a problem with cobbler. The virtual machine which has to be installed can't fecht the kickstart file. After booting the following error message is displayed : 

```bash
dracut-initqueue[574]: curl (22) The requested URL return error: 500 Internal Server Error
dracut-initqueue[574]: Warning: failed to fetch kickstart from http://XXX.XXX.X.X/cblr/svc/op/ks/system/<profile>
```
System : 

Oracle/RedHat Enterprise Linux 7.1
Python 2.7
Cobbler 2.6.9-1

```bash
# ls -l /usr/bin/pyth*
-rwxr-xr-x. 2 root root  12K Jun  2 21:01 /usr/bin/python3.4m
-rwxr-xr-x. 2 root root  12K Jun  2 21:01 /usr/bin/python3.4
-rwxr-xr-x. 1 root root 7.0K Jun 23 11:53 /usr/bin/python2.7
lrwxrwxrwx. 1 root root    9 Jun 23 15:39 /usr/bin/python3 -> python3.4
lrwxrwxrwx. 1 root root    9 Jun 24 13:16 /usr/bin/python2 -> python2.7
lrwxrwxrwx  1 root root    7 Jul  2 13:51 /usr/bin/python -> python2
```

Into the error_log I have the following messages : 

```
[Fri Jul 03 16:12:31.029205 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] mod_wsgi (pid=9386): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Fri Jul 03 16:12:31.029278 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] Traceback (most recent call last):
[Fri Jul 03 16:12:31.029346 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044]   File "/var/www/cobbler/svc/services.py", line 39, in application
[Fri Jul 03 16:12:31.029356 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044]     import yaml
[Fri Jul 03 16:12:31.029386 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] ImportError: No module named 'yaml'
[Fri Jul 03 16:12:35.038283 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] mod_wsgi (pid=9386): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Fri Jul 03 16:12:35.038353 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] Traceback (most recent call last):
[Fri Jul 03 16:12:35.038410 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044]   File "/var/www/cobbler/svc/services.py", line 39, in application
[Fri Jul 03 16:12:35.038420 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044]     import yaml
[Fri Jul 03 16:12:35.038448 2015] [wsgi:error] [pid 9386] [remote XXX.XXX.X.XXX:7044] ImportError: No module named 'yaml'
```

What I have tried ? : 

a) Start a python interpreter and run : import yaml

Result : 

```python
if we get the message :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'yaml'
```

b) I reinstall the modul like : yum reinstall PyYAML

Then I tired again and then the import yaml has succeeded.

c) Run the Virtual Machine to be new installed => same result in the error_log as decribed above.

Then I have copied services.py to /tmp and modify the script as below : 

```python
# sed -n 23,40p services.py 
# Only add standard python modules here. When running under a virtualenv other modules are not
# available at this point.
import os
import urllib
import cgi
import yaml

def application(environ, start_response):

    if 'VIRTUALENV' in environ and environ['VIRTUALENV'] != "":
        # VIRTUALENV Support
        # see http://code.google.com/p/modwsgi/wiki/VirtualEnvironments
        import site
        import distutils.sysconfig
        site.addsitedir(distutils.sysconfig.get_python_lib(prefix=environ['VIRTUALENV']))
        # Now all modules are available even under a virtualenv

    from cobbler.services import CobblerSvc
```

Then  I run it with : python /tmp/services.py and I got no error messages. This and the execution of the script (Quick example into the section "Documentation" http://pyyaml.org/wiki/PyYAML) give no errors.
That's confirm in my opinion that the yaml module can be successfully loaded by python.

I don't understand why this is not the case when cobbler do it by itself.

Maybe this question found already a solution. Can you please adivce ?

Thank you in advance.

Kind regards,

Pascal Chenevas

**Comment by pascal-chenevas** [comment]
I have found why I have this problem...

In my case I have differents version of python and it seems that the version 3.4 was taken as default. As PyYAML is for python 2.7, a manual load of this module into the python (version 3.4) interpreter falied.

After a full removing of this python version, cobbler is now able to fetch the kickstart file and the machine can proceed automaticaly the installation.

Now : 

```bash
# ls -l /usr/bin/pyth*
-rwxr-xr-x. 1 root root 7.0K Jun 23 11:53 /usr/bin/python2.7
lrwxrwxrwx. 1 root root    9 Jun 24 13:16 /usr/bin/python2 -> python2.7
lrwxrwxrwx  1 root root    7 Jul  2 13:51 /usr/bin/python -> python2
```
Kind regards,

Pascal Chenevas
