### ISSUE TITLE
epel 7 reposync fails on RHEL 5

### ISSUE THREAD

**Issue by kruster** [cobbler/cobbler#1521]
hi all, 

I have this error from few weeks ! 

Version Cobbler : cobbler-2.4.8-1.el5
Os : RedHat 5.11

my repo config : 

Name                           : epel-rhel7-x86_64
Apt Components (apt only)      : 
Apt Dist Names (apt only)      : 
Arch                           : x86_64
Breed                          : yum
Comment                        : 
Createrepo Flags               : -c cache -C --update
Environment Variables          : {'http_proxy': 'proxy-http:8080'}
Keep Updated                   : True
Mirror                         : http://dl.fedoraproject.org/pub/epel/7/x86_64/
Mirror locally                 : True
Owners                         : ['admin']
Priority                       : 99
RPM List                       : []
Yum Options                    : {}

Error : 
task started: 2015-08-05_165740_reposync
task started (id=Reposync, time=Wed Aug  5 16:57:40 2015)
hello, reposync
run, reposync, run!
setting repo environment: http_proxy=proxy-http:8080
creating: /var/www/cobbler/repo_mirror/epel-rhel7-x86_64/.origin/epel-rhel7-x86_64.repo
running: /usr/bin/reposync -l -m -d --config=/var/www/cobbler/repo_mirror/epel-rhel7-x86_64/.origin/epel-rhel7-x86_64.repo --repoid=epel-rhel7-x86_64 --download_path=/var/www/cobbler/repo_mirror -a x86_64
4.4 kB     00:00     
3.7 MB     00:08     

received on stderr: Traceback (most recent call last):
  File "/usr/bin/reposync", line 291, in ?
    main()
  File "/usr/bin/reposync", line 179, in main
    my.doSackSetup(rpmUtils.arch.getArchList(opts.arch))
  File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 465, in doSackSetup
    return self._getSacks(archlist=archlist, thisrepo=thisrepo)
  File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 502, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.4/site-packages/yum/repos.py", line 260, in populateSack
    sack.populate(repo, mdtype, callback, cacheonly)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 168, in populate
    if self._check_db_version(repo, mydbtype):
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 226, in _check_db_version
    return repo._check_db_version(mdtype)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1226, in _check_db_version
    repoXML = self.repoXML
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1399, in <lambda>
    repoXML = property(fget=lambda self: self._getRepoXML(),
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1391, in _getRepoXML
    self._loadRepoXML(text=self)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1381, in _loadRepoXML
    return self._groupLoadRepoXML(text, ["primary"])
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1366, in _groupLoadRepoXML
    self._commonRetrieveDataMD(mdtypes)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1343, in _commonRetrieveDataMD
    misc.bunzipFile(dl_local, local)
  File "/usr/lib/python2.4/site-packages/yum/misc.py", line 615, in bunzipFile
    data = s_fn.read(1024000)
EOFError: compressed file ended before the logical end-of-stream was detected

Exception occured: cobbler.cexceptions.CX
Exception value: 'cobbler reposync failed'
Exception Info:
  File "/usr/lib/python2.4/site-packages/cobbler/utils.py", line 129, in die
    raise CX(msg)

Exception occured: cobbler.cexceptions.CX
Exception value: 'cobbler reposync failed'
Exception Info:
  File "/usr/lib/python2.4/site-packages/cobbler/action_reposync.py", line 125, in run
    self.sync(repo)
   File "/usr/lib/python2.4/site-packages/cobbler/action_reposync.py", line 169, in sync
    return self.yum_sync(repo)
   File "/usr/lib/python2.4/site-packages/cobbler/action_reposync.py", line 402, in yum_sync
    utils.die(self.logger,"cobbler reposync failed")
   File "/usr/lib/python2.4/site-packages/cobbler/utils.py", line 137, in die
    raise CX(msg)

reposync failed, tries left: 0
resetting repo environment: http_proxy=http://proxy-http:8080
reposync failed, retry limit reached, skipping
running: chown -R root:apache /var/www/cobbler/repo_mirror/epel-rhel7-x86_64
received on stdout: 
received on stderr: 
running: chmod -R 755 /var/www/cobbler/repo_mirror/epel-rhel7-x86_64
received on stdout: 
received on stderr: 
Exception occured: cobbler.cexceptions.CX
Exception value: 'overall reposync failed, at least one repo failed to synchronize'
Exception Info:
  File "/usr/lib/python2.4/site-packages/cobbler/utils.py", line 129, in die
    raise CX(msg)

Exception occured: cobbler.cexceptions.CX
Exception value: 'overall reposync failed, at least one repo failed to synchronize'
Exception Info:
  File "/usr/lib/python2.4/site-packages/cobbler/remote.py", line 87, in run
    rc = self._run(self)
   File "/usr/lib/python2.4/site-packages/cobbler/remote.py", line 247, in runner
    3), name=name, nofail=nofail, logger=self.logger)
   File "/usr/lib/python2.4/site-packages/cobbler/api.py", line 808, in reposync
    return reposync.run(name)
   File "/usr/lib/python2.4/site-packages/cobbler/action_reposync.py", line 154, in run
    utils.die(self.logger,"overall reposync failed, at least one repo failed to synchronize")
   File "/usr/lib/python2.4/site-packages/cobbler/utils.py", line 137, in die
    raise CX(msg)

!!! TASK FAILED !!!

Someone can help me ?

Thanks in advance,

**Comment by divad** [comment]
I have hit this problem as well, but isn't it a problem with Satellite rather than Cobbler?

**Comment by divad** [comment]
Or rather, with 'reposync'.

**Comment by divad** [comment]
Right, EPEL 7 uses xz files for its repodata. Sadly this means you need reposync to support xz, which requires the python package pyliblzma. That isn't available on RHEL5 and won't compile on it either.

**Comment by jmaas** [comment]
Thanks Divad... Hope this had helped @kruster .

We don't provide support Cobbler 2.4.x and RHEL5 anymore, so i'm closing this issue.
