### ISSUE TITLE
Cannot login on a fresh install

### ISSUE THREAD

**Issue by steph-ben** [cobbler/cobbler#1726]
After installing a fresh 2.8 release from RPM, I cannot login to the web portal
That's a little bit sad, since everything should work fine on a fresh install :-/

This looks like issue https://github.com/cobbler/cobbler/issues/641
However, distro_signatures file looks fine to me - and it's from fresh install

Any other idea ?

```
[root@linux log]# rpm -qa | grep cobbler
cobbler-2.8.0-12.1.noarch
cobbler-web-2.8.0-12.1.noarch

[root@linux log]# cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

==> cobbler/cobbler.log <==
Wed Oct 19 13:44:05 2016 - INFO | Exception occured: <type 'exceptions.AttributeError'>
Wed Oct 19 13:44:05 2016 - INFO | Exception value: 'module' object has no attribute 'authenticate'
Wed Oct 19 13:44:05 2016 - INFO | Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 2074, in _dispatch
    return method_handle(*params)
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1873, in login
    if self.__validate_user(login_user,login_password):
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1770, in __validate_user
    return self.api.authenticate(input_user,input_password)
   File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 1009, in authenticate
    rc = self.authn.authenticate(self,user,password)
```

**Comment by jmaas** [comment]
Again, i cant reproduce on Centos 7 with clean RPM install from source.

**Comment by jmaas** [comment]
Does Cobbler even work from the cli?
As root try to run `cobbler version`

**Comment by jmaas** [comment]
Can you do:

```
[root@centos-7-amd64 cobbler]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cobbler.modules.authn_configfile
>>> 
```

**Comment by steph-ben** [comment]
Here you go:

```
[root@linux ~]# cobbler version
Cobbler 2.8.0
  source: ?, ?
  build time: Thu Nov 24 20:08:09 2016
```

```
[root@linux ~]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cobbler.modules.authn_configfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/cobbler/modules/authn_configfile.py", line 27, in <module>
    from utils import md5
ImportError: No module named utils
```

Maybe it should calls for *cobbler*.utils ?
```
>>> import cobbler.utils
>>> cobbler.utils.md5("cobbler")
<md5 HASH object @ 0x12195d0>
>>> cobbler.utils.__file__
'/usr/lib/python2.6/site-packages/cobbler/utils.pyc'
```

**Comment by jmaas** [comment]
Are you using the RPMS from the opensuse build service?

**Comment by steph-ben** [comment]
I installed them from this link
http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/CentOS_6/noarch/

Doing
```
yum install http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/CentOS_6/noarch/cobbler-2.8.0-12.7.noarch.rpm
yum install http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/CentOS_6/noarch/cobbler-web-2.8.0-12.7.noarch.rpm
```

**Comment by jmaas** [comment]
Yes, we stopped providing packages due to lack of resources.
Sorry!
