### ISSUE TITLE
Install using # python setup.py install on debian raises TypeError exception

### ISSUE THREAD

**Issue by abousselmi** [cobbler/cobbler#1750]
Hi !
When trying to setup Cobbler using source code in a debian 8 by doing:
`# python setup.py install`
the installation unrolls until a TypeError exception is raised. Here is the trace back:

```
Traceback (most recent call last):
  File "setup.py", line 730, in <module>
    ("%szone_templates" % etcpath,                []),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 373, in run
    path = os.path.join(self.root + libpath, 'webui_sessions')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Thanks :)

**Comment by jmaas** [comment]
Fixed in master and release28.
