### ISSUE TITLE
ldap login issues on 2.8.0, logs point to authn_ldap.py

### ISSUE THREAD

**Issue by agentguerry** [cobbler/cobbler#1780]
I have cobber 2.8.0-12 running on rhel 6 64bit along with python 2.6.6
I am using LDAP to authenticate, and have confirmed that my ldap does work, but when I am attempting to log into the web interface for cobbler I am seeing the following error:

Mon Apr 24 09:57:18 2017 - INFO | Exception occured: <type 'exceptions.IOError'>
Mon Apr 24 09:57:18 2017 - INFO | Exception value: [Errno 9] Bad file descriptor
Mon Apr 24 09:57:18 2017 - INFO | Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 2074, in _dispatch
    return method_handle(*params)
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1873, in login
    if self.__validate_user(login_user,login_password):
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1770, in __validate_user
    return self.api.authenticate(input_user,input_password)
   File "/usr/lib/python2.6/site-packages/cobbler/api.py", line 1009, in authenticate
    rc = self.authn.authenticate(self,user,password)
   File "/usr/lib/python2.6/site-packages/cobbler/modules/authn_ldap.py", line 100, in authenticate
    traceback.print_exc()
   File "/usr/lib64/python2.6/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
   File "/usr/lib64/python2.6/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
   File "/usr/lib64/python2.6/traceback.py", line 13, in _print
    file.write(str+terminator)

I have a 2nd cobbler setup in another separate environment, and its using the same OS, kernel, python and cobbler version and that one works.  Looking to see what I can potentially compare to fix the broken one.

**Comment by jmaas** [comment]
Any progress on this?

Given your explanation this doesnt seem to be a bug.
I  have 2.8 working against an IPA server.

**Comment by jmaas** [comment]
I am closing this one, please report back if you still think this is a bug.

Thanks!
