### ISSUE TITLE
Cobbler Web timeout Errno 110

### ISSUE THREAD

**Issue by hightekjonathan** [cobbler/cobbler#2008]
I'm trying to install Cobbler Web for CentOS 7. I already downgraded Django to 1.9..* as mentioned in another issue. Now it is just constantly trying to load in Chrome and Safari.

Output of /var/log/httpd
```log
[Wed Jan 23 15:06:24.529668 2019] [:error] [pid 6402] Internal Server Error: /cobbler_web/
[Wed Jan 23 15:06:24.529732 2019] [:error] [pid 6402] Traceback (most recent call last):
[Wed Jan 23 15:06:24.529743 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Wed Jan 23 15:06:24.529753 2019] [:error] [pid 6402]     response = self.process_exception_by_middleware(e, request)
[Wed Jan 23 15:06:24.529762 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Jan 23 15:06:24.529771 2019] [:error] [pid 6402]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Jan 23 15:06:24.529779 2019] [:error] [pid 6402]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 37, in index
[Wed Jan 23 15:06:24.529788 2019] [:error] [pid 6402]     if not test_user_authenticated(request): return login(request,next="/cobbler_web", expired=True)
[Wed Jan 23 15:06:24.529797 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Wed Jan 23 15:06:24.529805 2019] [:error] [pid 6402]     response = view_func(request, *args, **kwargs)
[Wed Jan 23 15:06:24.529814 2019] [:error] [pid 6402]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 1292, in login
[Wed Jan 23 15:06:24.529822 2019] [:error] [pid 6402]     token = remote.login("", utils.get_shared_secret())
[Wed Jan 23 15:06:24.529831 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
[Wed Jan 23 15:06:24.529839 2019] [:error] [pid 6402]     return self.__send(self.__name, args)
[Wed Jan 23 15:06:24.529847 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
[Wed Jan 23 15:06:24.529856 2019] [:error] [pid 6402]     verbose=self.__verbose
[Wed Jan 23 15:06:24.529864 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
[Wed Jan 23 15:06:24.529872 2019] [:error] [pid 6402]     return self.single_request(host, handler, request_body, verbose)
[Wed Jan 23 15:06:24.529880 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
[Wed Jan 23 15:06:24.529889 2019] [:error] [pid 6402]     self.send_content(h, request_body)
[Wed Jan 23 15:06:24.529897 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
[Wed Jan 23 15:06:24.529905 2019] [:error] [pid 6402]     connection.endheaders(request_body)
[Wed Jan 23 15:06:24.529913 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
[Wed Jan 23 15:06:24.529921 2019] [:error] [pid 6402]     self._send_output(message_body)
[Wed Jan 23 15:06:24.529929 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
[Wed Jan 23 15:06:24.529938 2019] [:error] [pid 6402]     self.send(msg)
[Wed Jan 23 15:06:24.529946 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/httplib.py", line 843, in send
[Wed Jan 23 15:06:24.529954 2019] [:error] [pid 6402]     self.connect()
[Wed Jan 23 15:06:24.529962 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/httplib.py", line 824, in connect
[Wed Jan 23 15:06:24.529970 2019] [:error] [pid 6402]     self.timeout, self.source_address)
[Wed Jan 23 15:06:24.529978 2019] [:error] [pid 6402]   File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
[Wed Jan 23 15:06:24.529987 2019] [:error] [pid 6402]     raise err
[Wed Jan 23 15:06:24.529995 2019] [:error] [pid 6402] error: [Errno 110] Connection timed out
```

It looks like it is having issues creating to socket in python? Is this a known issue, and being resolved in version 3, or did I do something wrong?

**Comment by jmaas** [comment]
See if you can reach apache on localhost:80 (telnet localhost 80).

**Comment by jmaas** [comment]
The timeout suggests IPtables is in the way, try unloading that.

**Comment by hightekjonathan** [comment]
Thanks for replying. I have the firewall disabled completely, and stopped. I can telnet to 80 from the machine, and can pull up the apache welcome page by visiting 127.0.0.1. However when I try navigating to https://127.0.0.1/cobbler_web/ it just keeps trying to load, but never does. When going to 127.0.0.1/cobbler_web/ it gives me a 403 - permission denied.

**Comment by hightekjonathan** [comment]
Here is the output of `/var/log/cobbler/cobbler.log`

```
Sun Jan 27 03:45:02 2019 - INFO | 11 breeds and 81 OS versions read from the signature file
Sun Jan 27 03:45:02 2019 - DEBUG | API handle initialized
Sun Jan 27 03:45:02 2019 - DEBUG | XMLRPC running on 25151
Tue Jan 29 10:30:49 2019 - INFO | 11 breeds and 81 OS versions read from the signature file
Tue Jan 29 10:30:49 2019 - DEBUG | API handle initialized
Tue Jan 29 10:30:49 2019 - DEBUG | XMLRPC running on 25151
Tue Jan 29 10:45:44 2019 - INFO | 11 breeds and 81 OS versions read from the signature file
Tue Jan 29 10:45:44 2019 - DEBUG | API handle initialized
Tue Jan 29 10:45:44 2019 - DEBUG | XMLRPC running on 25151
```

There is no other file named `cobblerd.log` though.

**Comment by martindka** [comment]
You need to set the folder recursively with same user, group as it is in Apache config. 
Otherwise it won't work.

Pardon, this is basic with Apache.

**Comment by hightekjonathan** [comment]
@martindka What folder needs to be set? And if this has to change from the base install, why is it not covered in the installation instructions?

**Comment by martindka** [comment]
@hightekjonathan I used to use installation manuals which aren't good, unfortunatelly. It is plenty of it on the internet.
Maybe now Katello is so popular so Red Hat moved money to another way?! I don't know to be honestly.

I am not maintainer of this repo. I am just linux admin with Ansible knowledge who needs to fight still with bad installation manuals and I prefer Cobbler for future.

This folder **cobbler_webui_content** needs to be set to right user and group **apache**

**Comment by Laurel-rao** [comment]
I know the solution that resolved this issue, everybody attention here. 
<h1>Check you url isn't http</h1>
<h1>Because cobbler support https only!</h1>
- It's take a long time to resolve the questions.And it was exhausted me!!!

``` 
    # use this url
    https://192.168.1.110/cobbler_web/
```

**Comment by bomblevijay** [comment]
@Laurel-rao your solution is not working at all

**Comment by Laurel-rao** [comment]
emmm, a solution can't resolve every issue.Your environment and the way that you setup cobbler might cause cobbler be failure.
### please show your environment and some details like log file, the more infomation you provide,the faster we can help you.

**Comment by bomblevijay** [comment]
Hi Laurel

Forbidden
You don't have permission to access /cobbler_web/ on this server.


below is the error log 

tailf /var/log/httpd/ssl_error_log

test2 conf.d]# tailf /var/log/httpd/ssl_error_log
[Tue Jun 04 00:55:41.225963 2019] [:error] [pid 29925] [client 10.1.27.108:53229] access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required
[Tue Jun 04 04:34:34.750472 2019] [ssl:warn] [pid 14021] AH01909: RSA certificate configured for 10.1.27.112:443 does NOT include an ID which matches the server name
[Tue Jun 04 04:34:35.164244 2019] [ssl:warn] [pid 14021] AH01909: RSA certificate configured for 10.1.27.112:443 does NOT include an ID which matches the server name
[Tue Jun 04 04:34:54.776925 2019] [:error] [pid 14026] [client 10.1.27.108:59277] access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required
[Tue Jun 04 04:34:56.843207 2019] [:error] [pid 14026] [client 10.1.27.108:59277] access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required
[Tue Jun 04 05:02:42.388114 2019] [ssl:warn] [pid 14637] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 04 05:02:42.388154 2019] [ssl:warn] [pid 14637] AH01909: RSA certificate configured for 10.1.27.112:443 does NOT include an ID which matches the server name
[Tue Jun 04 05:02:42.802488 2019] [ssl:warn] [pid 14637] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 04 05:02:42.802545 2019] [ssl:warn] [pid 14637] AH01909: RSA certificate configured for 10.1.27.112:443 does NOT include an ID which matches the server name
[Tue Jun 04 05:03:51.212680 2019] [:error] [pid 14645] [client 10.1.27.108:60228] access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required
 access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required

**Comment by watologo1** [comment]
This certainly has to do with your apache SSL setup.
You can try to remove all:
        <IfModule mod_ssl.c>
            SSLRequireSSL
        </IfModule>
        <IfModule mod_nss.c>
            NSSRequireSSL
        </IfModule>

appearances in find /etc/apache2/ |grep cobbler
files and restart apache server.
But only do this temporarily or for test purposes, not for production. There you should setup SSL properly. Hope that helps.

**Comment by kwizart** [comment]
I think this issue should be closed. Looks like integration issue with https on cobbler_web

**Comment by SchoolGuy** [comment]
Indeed. No activity and apparently no Cobbler Issue. If needed, we can still reopen this one.
