### ISSUE TITLE
error: [Errno 113] No route to host

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2129]
Hello,

Cobbler version: Release28
OS: CentOS

Suddenly cobbler UI stop logging. 

When run cobbler check, it throws no route to host error as below.

```
httpd does not appear to be running and proxying cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cobbler/cli.py", line 251, in check_setup
    s.ping()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 113] No route to host
```

HTTP actually running
```
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-08-28 00:37:47 PDT; 4min 12s ago
     Docs: man:httpd(8)
           man:apachectl(8)
 Main PID: 2201 (httpd)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─2201 /usr/sbin/httpd -DFOREGROUND
           ├─2202 (wsgi:ertino_we -DFOREGROUND
           ├─2203 /usr/sbin/httpd -DFOREGROUND
           ├─2204 /usr/sbin/httpd -DFOREGROUND
           ├─2205 /usr/sbin/httpd -DFOREGROUND
           ├─2206 /usr/sbin/httpd -DFOREGROUND
           └─2207 /usr/sbin/httpd -DFOREGROUND

Aug 28 00:37:47 ZTP-Server1 systemd[1]: Starting The Apache HTTP Server...
Aug 28 00:37:47 ZTP-Server1 httpd[2201]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::d07:8e55:2c6d:3a1...is message
Aug 28 00:37:47 ZTP-Server1 systemd[1]: Started The Apache HTTP Server.
Hint: Some lines were ellipsized, use -l to show in full.
```

How to address this issue?

Thanks,

Mohan

**Comment by MohanrajBabu** [comment]
DHCP lease expired, system has got new IP address(192.168.23.22).

IP address(192.168.23.17) configured for next_server and server was the old IP in /etc/cobbler/settings and its caused the problem. 

Reconfigured the system IP with static IP address and configured the same IP in settings file. Its now working fine.
