### ISSUE TITLE
centos 7  web error

### ISSUE THREAD

**Issue by hzjnet** [cobbler/cobbler#2177]
````
[root@cs7opip213-ipq4x cobbler]# lsb_release -ra
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
````

````
[root@cs7opip213-ipq4x cobbler]# cobbler --version 
Cobbler 2.8.5
  source: ?, ?
  build time: Fri Aug 30 13:43:26 2019
[root@cs7opip213-ipq4x cobbler]# httpd -V
Server version: Apache/2.4.6 (CentOS)
Server built:   Aug  8 2019 11:41:18
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
````

````
[root@cs7opip213-ipq4x cobbler]# cobbler profile report 
Name                           : CentOS7-x86_64-web_install
TFTP Boot Files                : {}
Comment                        : 
DHCP Tag                       : default
Distribution                   : CentOS_7-x86_64
Enable gPXE?                   : 0
Enable PXE Menu?               : 1
Fetchable Files                : {}
Kernel Options                 : {'biosdevname': '0', 'net.ifnames': '0'}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/cobbler/kickstarts/cs7h.web.ks
Kickstart Metadata             : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 : 
Internal proxy                 : 
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : xenpv

Name                           : CentOS7-x86_64-nfs_install
TFTP Boot Files                : {}
Comment                        : 
DHCP Tag                       : default
Distribution                   : CentOS_7-x86_64
Enable gPXE?                   : 0
Enable PXE Menu?               : 1
Fetchable Files                : {}
Kernel Options                 : {'biosdevname': '0', 'net.ifnames': '0'}
Kernel Options (Post Install)  : {}
Kickstart                      : /var/lib/cobbler/kickstarts/cs7h.nfs.ks
Kickstart Metadata             : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Owners                         : ['admin']
Parent Profile                 : 
Internal proxy                 : 
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : 1
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : xenpv
````

````
[root@cs7opip213-ipq4x cobbler]# ls -la /var/lib/cobbler/kickstarts/cs7h.nfs.ks /var/lib/cobbler/kickstarts/cs7h.web.ks
-rw------- 1 apache apache 1494 Oct 19 13:46 /var/lib/cobbler/kickstarts/cs7h.nfs.ks
-rw------- 1 apache apache 1522 Oct 19 13:46 /var/lib/cobbler/kickstarts/cs7h.web.ks
````

````
[root@cs7opip213-ipq4x cobbler]# rpm -qa|grep django
python-django16-bash-completion-1.6.11.7-5.el7.noarch
python-django-bash-completion-1.11.23-1.el7.noarch
python2-django16-1.6.11.7-5.el7.noarch
````

````
[root@cs7opip213-ipq4x cobbler]# cobbler validateks
task started: 2019-10-19_195944_validateks
task started (id=Kickstart Validation, time=Sat Oct 19 19:59:44 2019)
----------------------------
osversion: rhel7
checking url: http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-web_install
running: /usr/bin/ksvalidator -v "rhel7" "http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-web_install"
received on stdout: Error reading http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-web_install:
[Errno 14] HTTP Error 500 - Internal Server Error

received on stderr: 
Potential templating errors:
Unknown variable found at line 30, column 31: '$apMx2OG'
Unknown variable found at line 37, column 48: '$gjSAUAPsK'
----------------------------
osversion: rhel7
checking url: http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-nfs_install
running: /usr/bin/ksvalidator -v "rhel7" "http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-nfs_install"
received on stdout: Error reading http://10.10.4.213/cblr/svc/op/ks/profile/CentOS7-x86_64-nfs_install:
[Errno 14] HTTP Error 500 - Internal Server Error

received on stderr: 
Potential templating errors:
Unknown variable found at line 30, column 22: '$qq7L5r2q'
Unknown variable found at line 37, column 48: '$gjSAUAPsK'
*** potential errors detected in kickstarts ***
!!! TASK FAILED !!!
````
````
[root@cs7opip213-ipq4x httpd]# pip3.6 install -i https://pypi.tuna.tsinghua.edu.cn/simple pyyaml==5.1.2 --upgrade
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting pyyaml==5.1.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 576kB/s 
Installing collected packages: pyyaml
  Found existing installation: PyYAML 5.1
    Uninstalling PyYAML-5.1:
      Successfully uninstalled PyYAML-5.1
  Running setup.py install for pyyaml ... done
Successfully installed pyyaml-5.1.2
````
````
[root@cs7opip213-ipq4x httpd]# cat error_log 
[Sat Oct 19 22:29:37.280127 2019] [suexec:notice] [pid 6445] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sat Oct 19 22:29:37.308191 2019] [lbmethod_heartbeat:notice] [pid 6445] AH02282: No slotmem from mod_heartmonitor
[Sat Oct 19 22:29:37.320508 2019] [mpm_prefork:notice] [pid 6445] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.2 Python/3.6 configured -- resuming normal operations
[Sat Oct 19 22:29:37.320556 2019] [core:notice] [pid 6445] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sat Oct 19 22:29:38.820316 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46389] mod_wsgi (pid=6446): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Sat Oct 19 22:29:38.820674 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46389] Traceback (most recent call last):
[Sat Oct 19 22:29:38.820701 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46389]   File "/var/www/cobbler/svc/services.py", line 40, in application
[Sat Oct 19 22:29:38.820707 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46389]     from cobbler.services import CobblerSvc
[Sat Oct 19 22:29:38.820724 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46389] ModuleNotFoundError: No module named 'cobbler'
[Sat Oct 19 22:29:38.919801 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46391] mod_wsgi (pid=6446): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Sat Oct 19 22:29:38.919925 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46391] Traceback (most recent call last):
[Sat Oct 19 22:29:38.919950 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46391]   File "/var/www/cobbler/svc/services.py", line 40, in application
[Sat Oct 19 22:29:38.919955 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46391]     from cobbler.services import CobblerSvc
[Sat Oct 19 22:29:38.919971 2019] [wsgi:error] [pid 6446] [remote 10.10.4.213:46391] ModuleNotFoundError: No module named 'cobbler'
````

why ??

**Comment by SchoolGuy** [comment]
@hzjnet Just a wild guess but is there maybe a firewall preventing the communication? I have never played with CentOS so it is hard for me to help you properly.

**Comment by opoplawski** [comment]
Several comments:
- Initial error looks like a template rendering error.  What is the contents of /var/lib/cobbler/kickstarts/cs7h.nfs.ks ?
- Don't run pip install as root - it even tells you that it is a bad idea.  And what even prompted you to try that in the first place?
- The apache error_log seems to indicate that you are trying to run the python 2 cobbler 2.8.5 via a python 3.6 mod_wsgi which isn't going to work.

I suspect that things are hopelessly muddled at this point and you are better off starting over and decided whether you are going to use distro provided rpms or not.

**Comment by SchoolGuy** [comment]
No acitvity for a long time, also this is an old release which won't be maintained anymore. If the problem persists with newer versions please reopen and give additional information or open a new issue.
