### ISSUE TITLE
installation issues after recent changes

### ISSUE THREAD

**Issue by DwayneGit** [cobbler/cobbler#2232]
After commit c46abca11dca886411fc95802a2cbaa66fdb691b the deletion of the debian make rpms errors out on after not being able to find the folder same thing with the patches folder.

After commenting out the following:
```
...
#@cp debian/cobbler.dsc release/
#@cp debian/changelog release/debian.changelog
 #@cp debian/control release/debian.control
 #@cp debian/rules release/debian.rules
...
#cp patches/*.patch rpm-build/
```
i run into this error:
```
...
cp dist/*.gz rpm-build/
#cp patches/*.patch rpm-build/
rpmbuild --define "_topdir %(pwd)/rpm-build" \
--define "_builddir %{_topdir}" \
--define "_rpmdir %{_topdir}" \
--define "_srcrpmdir %{_topdir}" \
--define "_specdir %{_topdir}" \
--define '_rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' \
--define "_sourcedir  %{_topdir}" \
-ba cobbler.spec
error: File /usr/share/cobbler/rpm-build/cobbler-3.0.99.tar.gz: No such file or directory
```

in the most recent code i run into the following error on make install:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 333, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinx.ext.githubpages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 688, in <module>
    ("%s/man8" % docpath, glob("build/sphinx/man/*.8")),
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 130, in run
    _build.run(self)
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/sphinx/setup_command.py", line 158, in run
    freshenv=self.fresh_env)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 336, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension sphinx.ext.githubpages (exception: No module named 'sphinx.ext.githubpages')
```
which can be bypassed by commenting out 'sphinx.ext.githubpage' in docs/conf.py

**Comment by thiller2018** [comment]
Just sent a PR to fix most of the issues

**Comment by SchoolGuy** [comment]
PR: https://github.com/cobbler/cobbler/pull/2233

**Comment by DwayneGit** [comment]
Do you know how to get around the last part -> sphinx.ext.githubpage error?
Is there a package that needs to be install beyond sphinx?

**Comment by SchoolGuy** [comment]
@DwayneGit Yes of course and it is listed in the docs requirements file.
