### ISSUE TITLE
502 Proxy Error when running multiple concurrent cobbler CLI

### ISSUE THREAD

**Issue by pkqsun** [cobbler/cobbler#2298]
### Version

Cobbler 2.8.5

### Background
We have 80 servers to install the OS via cobbler. Initially, we did below stps one by one in sequence by python script:

cobbler add distro    // only one distro
              |
cobbler add profile   // profile per group, 5 or 4 profiles
              |
cobbler add system  // one host as one system, only assign names and create the system
              |
cobbler edit system  // 8 NICs to edit and assign the IP address

However, it cost about 20 minutes to prepare local cobbler env for above steps and we plan to reduce it.

### Plan
We change to use python concurrent.futures.ThreadPoolExecutor() for multiple concurrent jobs to add and edit system.

`    
with concurrent.futures.ThreadPoolExecutor(max_workers=host_number) as executor:                                                                             
         executor.map(add_system, (str(x) for x in list_host_names)) 
`

### Question

When use multiple concurrent cobbler CLI with thread, we meet below issue related with xmlrpclib:

```
2020-03-05 04:53:08,830  INFO: Add system host75 to cobbler failed
2020-03-05 04:53:08,841 DEBUG: Traceback (most recent call last):
2020-03-05 04:53:08,841 DEBUG:   File "/usr/bin/cobbler", line 36, in <module>
2020-03-05 04:53:08,841 DEBUG:     sys.exit(app.main())
2020-03-05 04:53:08,841 DEBUG:   File "/usr/lib/python2.7/site-packages/cobbler/cli.py", line 662, in main
2020-03-05 04:53:08,841 DEBUG:     rc = cli.run(sys.argv)
2020-03-05 04:53:08,842 DEBUG:   File "/usr/lib/python2.7/site-packages/cobbler/cli.py", line 279, in run
2020-03-05 04:53:08,842 DEBUG:     self.object_command(object_type, object_action)
2020-03-05 04:53:08,842 DEBUG:   File "/usr/lib/python2.7/site-packages/cobbler/cli.py", line 382, in object_command
2020-03-05 04:53:08,842 DEBUG:     self.remote.xapi_object_edit(object_type, options.name, object_action, utils.strip_none(vars(options), omit_none=True), self.token)
2020-03-05 04:53:08,842 DEBUG:   File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
2020-03-05 04:53:08,842 DEBUG:     return self.__send(self.__name, args)
2020-03-05 04:53:08,842 DEBUG:   File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
2020-03-05 04:53:08,842 DEBUG:     verbose=self.__verbose
2020-03-05 04:53:08,842 DEBUG:   File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
2020-03-05 04:53:08,843 DEBUG:     return self.single_request(host, handler, request_body, verbose)
2020-03-05 04:53:08,843 DEBUG:   File "/usr/lib64/python2.7/xmlrpclib.py", line 1321, in single_request
2020-03-05 04:53:08,843 DEBUG:     response.msg,
2020-03-05 04:53:08,843 DEBUG: xmlrpclib.ProtocolError: <ProtocolError for 172.16.1.10:80/cobbler_api: 502 Proxy Error>
```

When I try to reduce the max_workers/concurrent thread number to about 20, above issue disappeared. Refer to #607,  when I change/add the Timeout 120 in /etc/httpd/conf/httpd.conf, the 
concurrent thread number increases to about 30.
With more concurrent thread, above xmlrpclib 502 proxy issue always happened.

I want to get some suggestion or proposal from your team.

Maybe some other ways for running multiple concurrent cobbler CLIs is also OK for me.

Thanks in advance.

**Comment by SchoolGuy** [comment]
1. You are trying to develop Cobbler 2.x.x which won't be developed any further from my side at least. There are no plans for a future release
2. What you are trying to achieve will never work in a way you desire. See this stackoverflow post: https://stackoverflow.com/questions/1589150/python-xmlrpc-with-concurrent-requests
3. However if you are patient, I am planning to extend Cobbler 3 with a REST API if Cobbler 3 is stable enough. If you want to help you are welcome to help to contribute.

**Comment by pkqsun** [comment]
@SchoolGuy 
Thanks a lot for your info, I will change my design.
Currently we still use cobbler 2.8.5 as we tested on this old version.
Moreover, we plan to change to latest 3.x nearby middle of April.
I am glad to test 3.x REST API at that time if you need.

Indeed, we also private build the 3.0 version and just in try. The big concern for me is that there is no repo to yum install or pip3 install cobbler with latest version.

**Comment by SchoolGuy** [comment]
@pkqsun I am in the progress of recovering the pip repo (which is currently not accessible). Also there are yum repos. EPEL has currently even Cobbler 3.x.x available.

I don't think REST will be available that quickly. Currently development is slow because there is much to do and the project has not that much regular contributors. But let's see if I can make it happen...

**Comment by pkqsun** [comment]
@SchoolGuy ,
Sure, I would have a try to install 3.x with EPEL.
Just ping me when REST is available, glad to be one micro contributor.
