### ISSUE TITLE
cobbler behind reverse proxy and using remote_user sso (mod_auth_cas) issues

### ISSUE THREAD

**Issue by Wildcarde** [cobbler/cobbler#2336]
### Version

2.8.5 - epel version for redhat 7 edit: correcting version info
### Question
This question is mostly 'has anybody done this, what could be causing this to fail':

I'm currently working on trying to get a cobbler server up and running inside a docker container with the current configuration (current work on this located here: https://github.com/PrincetonUniversity/pni-cobbler):
Traefik handles 80/443 traffic; it terminates ssl similar to putting something behind HAProxy just dynamically based on labels in a docker container instead of direct config

cobbler container runs behind traefik, supervisord hosts the services for httpd, cobblerd, tftpd (replacing systemd so stdout works, envvars pass thru correctly, etc).

httpd container uses mod_auth_cas to supply REMOTE_USER variable to the underlying django service, httpd is configured to have a vhost so it can be supplied an FQDN to respond to.

I've been trying to dial in the right behavior for different parts of the config to make this work right, and depending on what i do it swings between cert errors - this will happen both with valid letsencrypt certs and with traefik self-signed certs; unauthorized errors despite the users.conf file being populated. I'll be testing this with authn disabled shortly just to eliminate the possibility that cas_auth is breaking things but this is a known working configuration based on this reference implementation (https://github.com/PrincetonUniversity/traefik-apache-shim).

Differrent configs for 'client use http' and webserver port generate different errors depending on whether you set them to 0/80, 1/443; none appear to work as expected.
config for these and other variables are handled from our [augeaus template.](https://github.com/PrincetonUniversity/pni-cobbler/blob/master/cobblerd/augeas-modifications.augfile.template) I'll try and make a grid of settings combos -> error codes if that would be helpful. 

side answers, we are currently not using centos8 or fedora containers because they do not yet have mod_auth_cas modules for httpd.

**Comment by SchoolGuy** [comment]
@Wildcarde First of all. Get rid of that 2.4.5 that is so old... Please use at least 2.8.x or for gods sake 3.x.x but I guess you will do it anyway...

And no I don't know anyone doing this. If you get it to work, I would consider myself very happy if you could share this with us. This setup would enable us to run Cobbler completely in docker and this would certainly be very awesome.

Also I think the Gitter Chat may be interesting for you which should be linked in the `README.md`.

**Comment by SchoolGuy** [comment]
To answer that question a bit more in detail... - I don't think that there should be anything preventing you from doing it.

**Comment by Wildcarde** [comment]
I double checked the version info, it's 2.8.5, it's the version supplied by EPEL for centos 7 (I forced a rebuild real quick):

```
 cobbler                         x86_64 2.8.5-0.3.el7             epel    580 k
 cobbler-web                     noarch 2.8.5-0.3.el7             epel    289 k
```
I'll build out the error codes grid based on the different config settings because this is essentially non functional right now.  Is the system expected to work with self signed certs as that's much easier to test since I can do it locally vs. needing to spin up on a host with a test alias to point at.

**Comment by Wildcarde** [comment]
first two tests: self signed cert, port in cobbler set to 80, https client off, sslrequire toggled on/off:
I'm going to do these in small chunks otherwise it'll be an enormous comment.

## Self Sign Cert:
clients use https: 0
client port: 80
SSLRequireSSL enabled

website shows 'Forbidden'
logs:
```
cobblerd    | [Mon Apr 27 17:28:15.508860 2020] [ssl:error] [pid 30] [client 172.17.17.2:47594] AH02219: access to /usr/share/cobbler/web/ failed, reason: SSL connection required
cobblerd    |
cobblerd    | 2020-04-27 17:28:15,509 DEBG 'httpd' stdout output:
cobblerd    | 172.17.17.2 - - [27/Apr/2020:17:28:15 +0000] "GET / HTTP/1.1" 403 202
cobblerd    |
cobblerd    | 2020-04-27 17:28:15,740 DEBG 'httpd' stdout output:
cobblerd    | [Mon Apr 27 17:28:15.740156 2020] [ssl:error] [pid 30] [client 172.17.17.2:47594] AH02219: access to /usr/share/cobbler/web/favicon.ico failed, reason: SSL connection required, referer: https://self.local/

```

clients use https: 0
client port: 80
SSLRequireSSL disabled

webpage:
```
ProtocolError at /
<ProtocolError for self.local:80/cobbler_api: 302 Found>
Request Method:	GET
Request URL:	http://self.local/cobbler_web/
Django Version:	1.11.27
Exception Type:	ProtocolError
Exception Value:	
<ProtocolError for self.local:80/cobbler_api: 302 Found>
Exception Location:	/usr/lib64/python2.7/xmlrpclib.py in single_request, line 1321
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/usr/share/cobbler/web/cobbler_web',
 '/usr/share/cobbler/web',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages']
Server time:
```
logs:
```
cobblerd    | 2020-04-27 18:43:17,372 DEBG 'httpd' stdout output:
cobblerd    | 172.17.17.2 - gmcgrath [27/Apr/2020:18:43:17 +0000] "GET /favicon.ico HTTP/1.1" 404 209
cobblerd    | 
cobblerd    | 2020-04-27 18:43:19,438 DEBG 'httpd' stdout output:
cobblerd    | 172.17.16.2 - - [27/Apr/2020:18:43:19 +0000] "POST /cobbler_api HTTP/1.1" 302 265
cobblerd    | 
cobblerd    | 2020-04-27 18:43:19,440 DEBG 'httpd' stdout output:
cobblerd    | [Mon Apr 27 18:43:19.440153 2020] [:error] [pid 26] Internal Server Error: /cobbler_web/
cobblerd    | [Mon Apr 27 18:43:19.440171 2020] [:error] [pid 26] Traceback (most recent call last):
cobblerd    | [Mon Apr 27 18:43:19.440173 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
cobblerd    | [Mon Apr 27 18:43:19.440175 2020] [:error] [pid 26]     response = get_response(request)
cobblerd    | [Mon Apr 27 18:43:19.440176 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
cobblerd    | [Mon Apr 27 18:43:19.440177 2020] [:error] [pid 26]     response = self.process_exception_by_middleware(e, request)
cobblerd    | [Mon Apr 27 18:43:19.440179 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
cobblerd    | [Mon Apr 27 18:43:19.440180 2020] [:error] [pid 26]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cobblerd    | [Mon Apr 27 18:43:19.440182 2020] [:error] [pid 26]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 36, in index
cobblerd    | [Mon Apr 27 18:43:19.440183 2020] [:error] [pid 26]     if not test_user_authenticated(request): return login(request,next="/cobbler_web", expired=True)
cobblerd    | [Mon Apr 27 18:43:19.440184 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
cobblerd    | [Mon Apr 27 18:43:19.440186 2020] [:error] [pid 26]     response = view_func(request, *args, **kwargs)
cobblerd    | [Mon Apr 27 18:43:19.440187 2020] [:error] [pid 26]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 1279, in login
cobblerd    | [Mon Apr 27 18:43:19.440188 2020] [:error] [pid 26]     token = remote.login("", utils.get_shared_secret())
cobblerd    | [Mon Apr 27 18:43:19.440190 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
cobblerd    | [Mon Apr 27 18:43:19.440191 2020] [:error] [pid 26]     return self.__send(self.__name, args)
cobblerd    | [Mon Apr 27 18:43:19.440192 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
cobblerd    | [Mon Apr 27 18:43:19.440193 2020] [:error] [pid 26]     verbose=self.__verbose
cobblerd    | [Mon Apr 27 18:43:19.440195 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
cobblerd    | [Mon Apr 27 18:43:19.440196 2020] [:error] [pid 26]     return self.single_request(host, handler, request_body, verbose)
cobblerd    | [Mon Apr 27 18:43:19.440197 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1321, in single_request
cobblerd    | [Mon Apr 27 18:43:19.440198 2020] [:error] [pid 26]     response.msg,
cobblerd    | [Mon Apr 27 18:43:19.440200 2020] [:error] [pid 26] ProtocolError: <ProtocolError for self.local:80/cobbler_api: 302 Found>
cobblerd    | 
cobblerd    | 2020-04-27 18:43:19,459 DEBG 'httpd' stdout output:
cobblerd    | 172.17.16.2 - - [27/Apr/2020:18:43:19 +0000] "POST /cobbler_api HTTP/1.1" 302 265
cobblerd    | 
cobblerd    | 2020-04-27 18:43:19,511 DEBG 'httpd' stdout output:
cobblerd    | 172.17.17.2 - - [27/Apr/2020:18:43:19 +0000] "GET /cobbler_web/ HTTP/1.1" 500 94912
```

**Comment by Wildcarde** [comment]
## self signed cert
clients use https: 1
client port: 443
SSLRequireSSL disabled

website:
```
SSLError at /
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
Request Method:	GET
Request URL:	http://self.local/cobbler_web/
Django Version:	1.11.27
Exception Type:	SSLError
Exception Value:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
Exception Location:	/usr/lib64/python2.7/ssl.py in do_handshake, line 831
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:
['/usr/share/cobbler/web/cobbler_web',
 '/usr/share/cobbler/web',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages']
 ```

logs:
```
cobblerd    | 2020-04-27 19:03:33,462 DEBG 'httpd' stdout output:
cobblerd    | [Mon Apr 27 19:03:33.462624 2020] [:error] [pid 26] Internal Server Error: /cobbler_web/
cobblerd    | [Mon Apr 27 19:03:33.462657 2020] [:error] [pid 26] Traceback (most recent call last):
cobblerd    | [Mon Apr 27 19:03:33.462661 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
cobblerd    | [Mon Apr 27 19:03:33.462663 2020] [:error] [pid 26]     response = get_response(request)
cobblerd    | [Mon Apr 27 19:03:33.462666 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
cobblerd    | [Mon Apr 27 19:03:33.462669 2020] [:error] [pid 26]     response = self.process_exception_by_middleware(e, request)
cobblerd    | [Mon Apr 27 19:03:33.462671 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
cobblerd    | [Mon Apr 27 19:03:33.462674 2020] [:error] [pid 26]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cobblerd    | [Mon Apr 27 19:03:33.462676 2020] [:error] [pid 26]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 36, in index
cobblerd    | [Mon Apr 27 19:03:33.462679 2020] [:error] [pid 26]     if not test_user_authenticated(request): return login(request,next="/cobbler_web", expired=True)
cobblerd    | [Mon Apr 27 19:03:33.462681 2020] [:error] [pid 26]   File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
cobblerd    | [Mon Apr 27 19:03:33.462684 2020] [:error] [pid 26]     response = view_func(request, *args, **kwargs)
cobblerd    | [Mon Apr 27 19:03:33.462687 2020] [:error] [pid 26]   File "/usr/share/cobbler/web/cobbler_web/views.py", line 1279, in login
cobblerd    | [Mon Apr 27 19:03:33.462689 2020] [:error] [pid 26]     token = remote.login("", utils.get_shared_secret())
cobblerd    | [Mon Apr 27 19:03:33.462691 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
cobblerd    | [Mon Apr 27 19:03:33.462694 2020] [:error] [pid 26]     return self.__send(self.__name, args)
cobblerd    | [Mon Apr 27 19:03:33.462696 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
cobblerd    | [Mon Apr 27 19:03:33.462699 2020] [:error] [pid 26]     verbose=self.__verbose
cobblerd    | [Mon Apr 27 19:03:33.462701 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
cobblerd    | [Mon Apr 27 19:03:33.462703 2020] [:error] [pid 26]     return self.single_request(host, handler, request_body, verbose)
cobblerd    | [Mon Apr 27 19:03:33.462705 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
cobblerd    | [Mon Apr 27 19:03:33.462708 2020] [:error] [pid 26]     self.send_content(h, request_body)
cobblerd    | [Mon Apr 27 19:03:33.462710 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
cobblerd    | [Mon Apr 27 19:03:33.462712 2020] [:error] [pid 26]     connection.endheaders(request_body)
cobblerd    | [Mon Apr 27 19:03:33.462715 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/httplib.py", line 1052, in endheaders
cobblerd    | [Mon Apr 27 19:03:33.462717 2020] [:error] [pid 26]     self._send_output(message_body)
cobblerd    | [Mon Apr 27 19:03:33.462719 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/httplib.py", line 890, in _send_output
cobblerd    | [Mon Apr 27 19:03:33.462721 2020] [:error] [pid 26]     self.send(msg)
cobblerd    | [Mon Apr 27 19:03:33.462724 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/httplib.py", line 852, in send
cobblerd    | [Mon Apr 27 19:03:33.462726 2020] [:error] [pid 26]     self.connect()
cobblerd    | [Mon Apr 27 19:03:33.462728 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/httplib.py", line 1275, in connect
cobblerd    | [Mon Apr 27 19:03:33.462730 2020] [:error] [pid 26]     server_hostname=sni_hostname)
cobblerd    | [Mon Apr 27 19:03:33.462733 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
cobblerd    |
cobblerd    | 2020-04-27 19:03:33,463 DEBG 'httpd' stdout output:
cobblerd    | [Mon Apr 27 19:03:33.462735 2020] [:error] [pid 26]     _context=self)
cobblerd    | [Mon Apr 27 19:03:33.462738 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
cobblerd    | [Mon Apr 27 19:03:33.462741 2020] [:error] [pid 26]     self.do_handshake()
cobblerd    | [Mon Apr 27 19:03:33.462743 2020] [:error] [pid 26]   File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
cobblerd    | [Mon Apr 27 19:03:33.462745 2020] [:error] [pid 26]     self._sslobj.do_handshake()
cobblerd    | [Mon Apr 27 19:03:33.462748 2020] [:error] [pid 26] SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
cobblerd    |
cobblerd    | 2020-04-27 19:03:33,571 DEBG 'httpd' stdout output:
cobblerd    | 172.17.17.2 - - [27/Apr/2020:19:03:33 +0000] "GET /cobbler_web/ HTTP/1.1" 500 136232
```

**Comment by Wildcarde** [comment]
If we re-enable sslrequiressl we loop back to:
```
cobblerd    | 2020-04-27 19:14:54,039 DEBG 'httpd' stdout output:
cobblerd    | [Mon Apr 27 19:14:54.038899 2020] [ssl:error] [pid 27] [client 172.17.17.2:49062] AH02219: access to /usr/share/cobbler/web/cobbler.wsgi failed, reason: SSL connection required, referer: https://self.local/
cobblerd    | 
```
However this setting really shouldn't be necessary at all in this setup because traefik forcibly institutes http->https promotion so all future testing will be done with these segments removed from the config.

**Comment by SchoolGuy** [comment]
Okay I thought this through again... It should be possible but as always the disclaimer: Noone seems to have ever done that.

You have two configs from Cobbler-Side. `cobbler.conf` and `cobbler-web.conf`. That means you could run (like the default is) both on port 80. That means Cobbler only talks HTTP which is good because then you don't need to build your own images (if you use HTTPS the kernel etc needs these certs built in, if it can't then you will get strange errors). Then you let Traefik handle SSL termination. To close down the attack vector I would recommend to block via Traefik external (meaning out of the normal networks) requests against the cobbler API. Then I would expose (also via Traefik) the Cobbler API & TFTP Server to the data center side, to be able to install machines.

Layout:

```
      SSL            HTTP
User <---> Traefik <------> Cobbler Web (to the User) & Cobbler HTTP API (to the datacenter machines)
              ^
              | HTTP
              |
          Datacenter machines
```

If you do want to have HA for Cobbler I suspect that this wouldn't be possible for the reasons that Cobbler has no database (SQL, NoSQL). In theory yes but these modules are not tested, so please don't use them for production. Also the built-in caching will prevent you from depending on the filesystem "database". Please run only one instance of Cobbler at a time. What is indeed possible is that if one instance goes down you can start another one if all files and mounts for the distros/isos are available. The current behavior for Cobbler is to refuse to start if something is unavailable.

I have personally running Traefik V2 at my homeserver and I do have limited experience with creating such set-ups but I don't have enough machines at home to test this. And rebuilding such stuff in VM's is currently not worth the time as I am constantly bugfixing and documenting inside Cobbler.

Regarding CAS I can't say anything as I never had any point of contact with it.

**Comment by Wildcarde** [comment]
hmm, currently my traefik config is all or nothing around whether you use ssl or not which may be the source of the problems i'm running into. However I can make sure that the traefik server has a valid to the world ssl cert, is it not possible to tell the kernel to use the standard pki folder on initial setup to avoid issues with it being able to verify certs?

**Comment by SchoolGuy** [comment]
@dansou901 Said he wanted to take over, so I will leave the field to him.

**Comment by dansou901** [comment]
@Wildcarde, as I wrote in gitter chat already, in this case it is better to use a tcp router with tls passthrough and configure ssl inside the cobbler container itself. The certificate and key can be mounted in the container via a volume, you just need to extract it from the acme.json (I assume you are using Let's Encrypt for certificates). For that, please read https://github.com/containous/traefik/issues/2418.

**Comment by SchoolGuy** [comment]
We will provide instructions for setting up Cobbler behind a Proxy when having a Docker Container for production. Thus related to #2453
