### ISSUE TITLE
AlmaLinux 8.3 import error

### ISSUE THREAD

**Issue by crandalj** [cobbler/cobbler#2617]
### Describe the bug

```
[root@cobbler /etc/cobbler]# cobbler import --name=AlmaLinux8 --arch=x86_64 --path=/mnt
task started: 2021-04-15_132516_import
task started (id=Media import, time=Thu Apr 15 13:25:16 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 95, in run
    rc = self._run(self)

  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 295, in runner
    self.logger

  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 1489, in import_tree
    import_module = self.get_module_by_name("managers.import_signatures")\

!!! TASK FAILED !!!
```

### Steps to reproduce

1. prepare distro for import
2. cobbler import --name=AlmaLinux8 --arch=x86_64 --path=/mnt
3.receive error

### Expected behavior

Expected cobbler to finish import process so that the pxe boot profile could be used.

### Cobbler version

```
Cobbler 3.2.1
  source: c7fc767, Thu Mar 4 20:07:10 2021 +0100
  build time: Thu Apr 15 13:45:28 2021
```

### Cobbler log

```
isolinux/ldlinux.c32

         32,768  28%   75.65kB/s    0:00:01
        116,096 100%  268.03kB/s    0:00:00 (xfr#25, to-chk=6/38)
isolinux/libcom32.c32

         32,768  18%   75.47kB/s    0:00:01
        180,700 100%  415.21kB/s    0:00:00 (xfr#26, to-chk=5/38)
isolinux/libutil.c32

         22,804 100%   52.40kB/s    0:00:00
         22,804 100%   52.40kB/s    0:00:00 (xfr#27, to-chk=4/38)
isolinux/memtest

         32,768  17%   75.12kB/s    0:00:01
        182,704 100%  417.85kB/s    0:00:00 (xfr#28, to-chk=3/38)
isolinux/splash.png

            186 100%    0.43kB/s    0:00:00
            186 100%    0.43kB/s    0:00:00 (xfr#29, to-chk=2/38)
isolinux/vesamenu.c32

         26,788 100%   61.27kB/s    0:00:00
         26,788 100%   61.27kB/s    0:00:00 (xfr#30, to-chk=1/38)
isolinux/vmlinuz

         32,768   0%   74.77kB/s    0:02:06
      9,511,872 100%   18.63MB/s    0:00:00 (xfr#31, to-chk=0/38)

2021-04-15T13:25:23 - DEBUG | received on stderr:
2021-04-15T13:31:08 - INFO | REMOTE version; user(?)
```

### Additional information

Issue  #2194 seems to have the same error. It was supposed to have been fixed and merged in. Possible the file was reverted in a recent commit?

The cobbler was setup in CentOS 7 and built from the latest release32 branch.

**Comment by crandalj** [comment]
Issue likely from old version from yum conflicting with the newer version. Uninstall was performed but it's likely the /usr/local/lib/python3.6/site-packages/cobbler remained from previous install.

**Comment by crandalj** [comment]
Previous version was cobbler 2.8 which uses python 2 so reopening. Jumped to the wrong conclusion. Sorry! Going to leave it open and let someone more familiar with this issue hopefully tell me whether it's valid or not.

**Comment by SchoolGuy** [comment]
@nodeg It would be very cool if you could try to reproduce this on `master` (and if not occuring) then on the `release32` branch. If not I will try after the 5th of may...

**Comment by crandalj** [comment]
@SchoolGuy 

I updated my server to use the master branch and did a make devinstall. I also updated the cobbler package in pip3 with a reinstall since the service didn't want to come up.

```
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/etc/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2021-04-16 08:51:16 EDT; 3s ago
  Process: 31195 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=1/FAILURE)
  Process: 31194 ExecStart=/usr/local/bin/cobblerd -F (code=exited, status=0/SUCCESS)
 Main PID: 31194 (code=exited, status=0/SUCCESS)

Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: Traceback (most recent call last):
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: File "/usr/local/bin/cobblerd", line 79, in main
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: api = cobbler_api.CobblerAPI(is_cobblerd=True)
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 102, in __init__
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: module_loader.load_modules()
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: File "/usr/local/lib/python3.6/site-packages/cobbler/module_loader.py", line 79, in load_modules
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: __import_module(mod_path, modname)
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: File "/usr/local/lib/python3.6/site-packages/cobbler/module_loader.py", line 106, in __import_module
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: log_exc(logger)
Apr 16 08:51:16 cobbler.med-web.com cobblerd[31194]: TypeError: log_exc() takes 0 positional arguments but 1 was given

```

Once updated the service came up.

Reran the commands I tried originally and an error still.

```
[root@cobbler /cobbler]# cobbler version
Cobbler 3.2.1
  source: d6fa0b1, Fri Apr 9 14:07:36 2021 +0200
  build time: Fri Apr 16 12:47:31 2021
[root@cobbler /cobbler]# cobbler import --name=AlmaLinux8 --arch=x86_64 --path=/mnt
task started: 2021-04-16_090712_import
task started (id=Media import, time=Fri Apr 16 09:07:12 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Exception occurred: <class 'KeyError'>
Exception value: 'signatures'
Exception Info:
  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 95, in run
    rc = self._run(self)

  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 295, in runner
    self.logger

  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 1491, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/local/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 191, in run
    self.signature = self.scan_signatures()

  File "/usr/local/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 224, in scan_signatures
    for sig in sigdata["breeds"][breed][version]["signatures"]:

!!! TASK FAILED !!!
```

I retried with Debian 10 and that import appears to work. AlmaLinux is new, and I saw it should have a signature in cobbler so perhaps there's something wrong in detecting the signature or a malformed signature for AlmaLinux throwing an error when trying to be imported?

**Comment by SchoolGuy** [comment]
Thanks for your report! We don't have tests for this particular part and I never saw your error happening before. Sadly I can't play as much as desired with Cobbler myself so it will take some time but in May I will revisit this latest. Until then please be patient. :)

**Comment by nodeg** [comment]
I could **not** reproduce this on a fresh openSUSE Leap 15.3 VM with installed Cobbler from source (master branch).  I used the `AlmaLinux-8.3-x86_64-dvd.iso` ISO from https://ftp.fau.de/almalinux/8.3/isos/x86_64/.

```bash
$ cobbler version
Cobbler 3.2.1
  source: d6fa0b14, Fri Apr 9 14:07:36 2021 +0200
  build time: Mon Apr 26 07:03:23 2021

$ sudo mount -t iso9660 -o loop,ro /home/dom/host_files/AlmaLinux-8.3-x86_64-dvd.iso /mnt2

$ ll /mnt2
total 12
dr-xr-xr-x 4 root root 2048 Mar 26 01:45 AppStream
dr-xr-xr-x 4 root root 2048 Mar 26 01:45 BaseOS
dr-xr-xr-x 3 root root 2048 Mar 26 01:45 EFI
dr-xr-xr-x 3 root root 2048 Mar 26 01:45 images
dr-xr-xr-x 2 root root 2048 Mar 26 01:45 isolinux
-r--r--r-- 1 root root   84 Mar 26 01:45 media.repo
-r--r--r-- 1 root root  664 Mar 26 01:45 TRANS.TBL
```


```bash
$ cobbler import --name=almalinux83 --arch=x86_64 --path=/mnt2
task started: 2021-04-26_091137_import
task started (id=Media import, time=Mon Apr 26 09:11:37 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt2', 'almalinux83', None, None, None]
importing from a network location, running rsync to fetch the files first
mkdir: /srv/www/cobbler/distro_mirror/almalinux83-x86_64
running: rsync -a  '/mnt2/' /srv/www/cobbler/distro_mirror/almalinux83-x86_64 --progress
received on stdout: sending incremental file list
received on stderr: 
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /srv/www/cobbler/distro_mirror/almalinux83-x86_64:
creating new distro: almalinux83-x86_64
trying symlink: /srv/www/cobbler/distro_mirror/almalinux83-x86_64 -> /srv/www/cobbler/links/almalinux83-x86_64
running python triggers from /var/lib/cobbler/triggers/add/distro/pre/*
running shell triggers from /var/lib/cobbler/triggers/add/distro/pre/*
shell triggers finished successfully
mkdir: /srv/www/cobbler/images/almalinux83-x86_64
trying hardlink /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/vmlinuz -> /srv/www/cobbler/images/almalinux83-x86_64/vmlinuz
trying hardlink /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/initrd.img -> /srv/www/cobbler/images/almalinux83-x86_64/initrd.img
mkdir: /srv/tftpboot/images/almalinux83-x86_64
trying hardlink /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/vmlinuz -> /srv/tftpboot/images/almalinux83-x86_64/vmlinuz
trying hardlink /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/initrd.img -> /srv/tftpboot/images/almalinux83-x86_64/initrd.img
processing boot_files for distro: almalinux83-x86_64
skipping symlink, destination (/srv/www/cobbler/links/almalinux83-x86_64) exists
Writing template files for almalinux83-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running python trigger cobbler.modules.managers.genders
running shell triggers from /var/lib/cobbler/triggers/change/*
shell triggers finished successfully
running python triggers from /var/lib/cobbler/triggers/add/distro/post/*
running shell triggers from /var/lib/cobbler/triggers/add/distro/post/*
shell triggers finished successfully
creating new profile: almalinux83-x86_64
running python triggers from /var/lib/cobbler/triggers/add/profile/pre/*
running shell triggers from /var/lib/cobbler/triggers/add/profile/pre/*
shell triggers finished successfully
Writing template files for almalinux83-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running python trigger cobbler.modules.managers.genders
running shell triggers from /var/lib/cobbler/triggers/change/*
shell triggers finished successfully
running python triggers from /var/lib/cobbler/triggers/add/profile/post/*
running shell triggers from /var/lib/cobbler/triggers/add/profile/post/*
shell triggers finished successfully
associating repos
checking for rsync repo(s)
mkdir: /srv/www/cobbler/images/almalinux83-x86_64
mkdir: /srv/tftpboot/images/almalinux83-x86_64
processing boot_files for distro: almalinux83-x86_64
skipping symlink, destination (/srv/www/cobbler/links/almalinux83-x86_64) exists
Writing template files for almalinux83-x86_64
Writing template files for almalinux83-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
checking for rhn repo(s)
mkdir: /srv/www/cobbler/images/almalinux83-x86_64
mkdir: /srv/tftpboot/images/almalinux83-x86_64
processing boot_files for distro: almalinux83-x86_64
skipping symlink, destination (/srv/www/cobbler/links/almalinux83-x86_64) exists
Writing template files for almalinux83-x86_64
Writing template files for almalinux83-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
checking for yum repo(s)
starting descent into /srv/www/cobbler/distro_mirror/almalinux83-x86_64 for almalinux83-x86_64
processing repo at : /srv/www/cobbler/distro_mirror/almalinux83-x86_64/AppStream
need to process repo/comps: /srv/www/cobbler/distro_mirror/almalinux83-x86_64/AppStream
looking for /srv/www/cobbler/distro_mirror/almalinux83-x86_64/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/almalinux83-x86_64/AppStream/repodata
processing repo at : /srv/www/cobbler/distro_mirror/almalinux83-x86_64/BaseOS
need to process repo/comps: /srv/www/cobbler/distro_mirror/almalinux83-x86_64/BaseOS
looking for /srv/www/cobbler/distro_mirror/almalinux83-x86_64/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/almalinux83-x86_64/BaseOS/repodata
mkdir: /srv/www/cobbler/images/almalinux83-x86_64
mkdir: /srv/tftpboot/images/almalinux83-x86_64
processing boot_files for distro: almalinux83-x86_64
skipping symlink, destination (/srv/www/cobbler/links/almalinux83-x86_64) exists
Writing template files for almalinux83-x86_64
Writing template files for almalinux83-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
*** TASK COMPLETE ***
```

```bash
tree -L 3 /srv/www/cobbler/
/srv/www/cobbler/
├── distro_mirror
│   ├── almalinux83-x86_64
│   │   ├── AppStream
│   │   ├── BaseOS
│   │   ├── EFI
│   │   ├── images
│   │   ├── isolinux
│   │   ├── media.repo
│   │   └── TRANS.TBL
│   └── config
│       ├── almalinux83-x86_64-0.repo
│       └── almalinux83-x86_64-1.repo
├── images
│   └── almalinux83-x86_64
│       ├── initrd.img
│       └── vmlinuz
├── links
│   └── almalinux83-x86_64 -> /srv/www/cobbler/distro_mirror/almalinux83-x86_64
├── localmirror
├── misc
│   ├── anamon
│   └── anamon.init
├── pub
├── rendered
├── repo_mirror
└── svc
    └── services.py

18 directories, 9 files
```

```
$ cobbler distro report
Name                           : almalinux83-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {'tree': 'http://@@http_server@@/cblr/links/almalinux83-x86_64'}
TFTP Boot Files                : {}
Boot loader                    : grub
Breed                          : redhat
Comment                        : 
Fetchable Files                : {}
Initrd                         : /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/initrd.img
Kernel                         : /srv/www/cobbler/distro_mirror/almalinux83-x86_64/images/pxeboot/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : rhel8
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : ~
Remote Boot Kernel             : ~
Template Files                 : {}

$ cobbler profile report
Name                           : almalinux83-x86_64
Automatic Installation Template : sample.ks
Automatic Installation Metadata : {}
TFTP Boot Files                : {}
Comment                        : 
DHCP Tag                       : default
Distribution                   : almalinux83-x86_64
Enable gPXE?                   : False
Enable PXE Menu?               : True
Fetchable Files                : {}
DHCP Filename Override         : <<inherit>>
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Next Server Override           : <<inherit>>
Owners                         : ['admin']
Parent Profile                 : 
Proxy                          : 
Red Hat Management Key         : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : True
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 5
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : kvm
```

@crandalj Did you probably use the `minimal` or `boot` ISO of AlmaLinux?

**Comment by crandalj** [comment]
@nodeg I used the boot iso. I can't get the CentOS isos to load either. This was done on a CentOS 7 machine. So if there are any package differences between OpenSUSE and CentOS distributions for how cobbler operates then it wouldn't be caught.

I reinstalled from scratch and used CentOS 8 and still can't get imports working. I git cloned the latest, installed requirements for rpm build, built the rpms, and installed from the rpm built from source.

The following used http://centos.den.host-engine.com/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-boot.iso 

```
[root@cobbler isos]# cobbler version
Cobbler 3.2.1
  source: 9f997bfa, Mon Apr 26 12:10:06 2021 +0200
  build time: Tue Apr 27 13:30:39 2021

[root@cobbler isos]# cobbler import --name=CentOS8 --arch=x86_64 --path=/mnt
task started: 2021-04-27_132007_import
task started (id=Media import, time=Tue Apr 27 13:20:07 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt', 'CentOS8', None, None, None]
importing from a network location, running rsync to fetch the files first
mkdir: /var/www/cobbler/distro_mirror/CentOS8-x86_64
running: rsync -a  '/mnt/' /var/www/cobbler/distro_mirror/CentOS8-x86_64 --progress
received on stdout: sending incremental file list
received on stderr:
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Exception occurred: <class 'KeyError'>
Exception value: 'signatures'
Exception Info:
!!! TASK FAILED !!!
```

**Comment by nodeg** [comment]
> Edit: Attempted using full iso and it appears to of brought it in. So looks like minimal and boot just don't import?

Yes. At the momente Cobbler only support importing a full ISO (no boot/minimal/live). See [1.7.1. Download an ISO image](https://cobbler.readthedocs.io/en/latest/quickstart-guide.html#download-an-iso-image) and #2623.

**Comment by crandalj** [comment]
@nodeg That's a simple fix for an obscure error. I don't know a lot about the contents between a boot, minimal, and dvd/full iso but some kind of error message at that point of the import could mention they received this error due to possibly using a boot or minimal ISO.

Sorry this wasted time on chasing down a non-existent bug in the signatures.

**Comment by nodeg** [comment]
No problem. @SchoolGuy and I discussed that it would be nice to have a more visible alert on this. For the future our plan is to extend Cobbler to be able to parse and import boot/minimal/live ISOs, too. See #2623.
