### ISSUE TITLE
Rocky 8.4/Cobbler 8.4 won't launch

### ISSUE THREAD

**Issue by spikebike** [cobbler/cobbler#2802]
### Describe the bug

Trying to launch cobblerd results in:
```
# /usr/bin/cobblerd -F
Traceback (most recent call last):
  File "/usr/bin/cobblerd", line 75, in main
    api = cobbler_api.CobblerAPI(is_cobblerd=True)
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 98, in __init__
    self.dist, self.os_version = utils.os_release()
TypeError: 'NoneType' object is not iterable
```

### Steps to reproduce

1. Install Rocky-8.4
2. dnf install cobbler (from https://cobbler.readthedocs.io/en/latest/installation-guide.html)
3. dns module enable cobbler
4. dnf install cobbler
5. /usr/bin/cobblerd -F
6. Copying in old /etc/cobbler/* from a previous install makes no differences

### Expected behavior

I'd expect it to not crash, or if a package or file is missing, complain about it.

### Cobbler version

``` 
# dnf info cobbler
Last metadata expiration check: 1:31:45 ago on Wed 22 Sep 2021 06:23:08 PM EDT.
Available Packages
Name         : cobbler
Version      : 3.2.0
Release      : 2.module_el8+10474+71f42bad
Architecture : noarch
Size         : 582 k
Source       : cobbler-3.2.0-2.module_el8+10474+71f42bad.src.rpm
Repository   : epel-modular
Summary      : Boot server configurator
URL          : https://cobbler.github.io/
```

### Operating system
```
# cat /etc/redhat-release 
Rocky Linux release 8.4 (Green Obsidian)
```

### Cobbler log

It crashes immediately, nothing in cobbler.log

**Comment by spikebike** [comment]
Ah, it's already handled in:
https://github.com/cobbler/cobbler/issues/2749

I verified the mentioned temporary hack fixes it.
