### ISSUE TITLE
cobbler test can't find schema, while it is installed

### ISSUE THREAD

**Issue by jringoot** [cobbler/cobbler#2880]
Trying to set up cobbler on ubuntu 20.04

Doing a "cobbler check" and get this 

```
(cobbler) root@easy-install-me:/opt/cobbler# cobbler check
Traceback (most recent call last):
  File "/usr/local/bin/cobbler", line 16, in <module>
    import cobbler.cli as app
  File "/usr/local/lib/python3.8/dist-packages/cobbler/cli.py", line 32, in <module>
    from cobbler import power_manager
  File "/usr/local/lib/python3.8/dist-packages/cobbler/power_manager.py", line 36, in <module>
    from cobbler import utils
  File "/usr/local/lib/python3.8/dist-packages/cobbler/utils.py", line 47, in <module>
    from cobbler import enums, settings
  File "/usr/local/lib/python3.8/dist-packages/cobbler/settings/__init__.py", line 22, in <module>
    from schema import SchemaError, SchemaMissingKeyError, SchemaWrongKeyError
ModuleNotFoundError: No module named 'schema'
(cobbler) root@easy-install-me:/opt/cobbler#
```

while  pip says: schema is installed
```
(cobbler) root@easy-install-me:/opt/cobbler# pip install schema
Requirement already satisfied: schema in ./cobbler/lib/python3.8/site-packages (0.7.5)
Requirement already satisfied: contextlib2>=0.5.5 in ./cobbler/lib/python3.8/site-packages (from schema) (21.6.0)
(cobbler) root@easy-install-me:/opt/cobbler# 

```

**Comment by SchoolGuy** [comment]
@jringoot what version of Cobbler are you using?

**Comment by SchoolGuy** [comment]
It seems that the Cobbler code searches your system-wide packages and pip looks at the venv located elsewhere. Is this maybe a bug only in your environment?

**Comment by SchoolGuy** [comment]
@jringoot Any news?

**Comment by jringoot** [comment]
> @jringoot Any news?

Sorry I abandoned this, I have set up a 'simple' dhcpd+tftpd+pxe-linux+nginx environment to do the installs.
