### ISSUE TITLE
regression after enum changes

### ISSUE THREAD

**Issue by olafhering** [cobbler/cobbler#2912]
A regression between c8e4af8affed82781212937c7655fd01f8488fec..e507f402f5a6dd8d9c7b6bbb8ce14bcb2cae3003, maybe caused by #2901 

````
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: Traceback (most recent call last):
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/enums.py", line 30, in to_enum
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     return cls[value.upper()]
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib64/python3.8/enum.py", line 387, in __getitem__
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     return cls._member_map_[name]
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: KeyError: '<<INHERIT>>'
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: During handling of the above exception, another exception occurred:
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: Traceback (most recent call last):
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/cobbler_collections/manager.py", line 212, in deserialize
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     serializer.deserialize(collection)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/serializer.py", line 128, in deserialize
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     storage_module.deserialize(collection, topological)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/modules/serializers/file.py", line 160, in deserialize
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     collection.from_list(datastruct)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/cobbler_collections/collection.py", line 201, in from_list
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     item = self.factory_produce(self.api, item_dict)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/cobbler_collections/systems.py", line 50, in factory_produce
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     new_system.from_dict(item_dict)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/items/system.py", line 844, in from_dict
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     super().from_dict(dictionary)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/items/item.py", line 793, in from_dict
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     setattr(self, lowered_key, dictionary[key])
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/items/system.py", line 1584, in virt_disk_driver
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     self._virt_disk_driver = enums.VirtDiskDrivers.to_enum(driver)
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/enums.py", line 36, in to_enum
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     raise ValueError(f"{value} must be one of {list(cls)}")
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: ValueError: <<inherit>> must be one of [<VirtDiskDrivers.INHERTIED: '<<inherit>>'>, <VirtDiskDrivers.RAW: 'raw'>, <VirtDiskDrivers.QCOW2: 'qcow2'>, <VirtDiskDrivers.QED: 'qed'>, <VirtDiskDrivers.VDI: 'vdi'>, <VirtDiskDrivers.VDMK: 'vdmk'>]
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: The above exception was the direct cause of the following exception:
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: Traceback (most recent call last):
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/bin/cobblerd", line 91, in main
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     api = cobbler_api.CobblerAPI(is_cobblerd=True, settingsfile_location=options.config,
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/api.py", line 106, in __init__
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     self.deserialize()
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/api.py", line 1647, in deserialize
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     return self._collection_mgr.deserialize()
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:   File "/usr/lib/python3.8/site-packages/cobbler/cobbler_collections/manager.py", line 214, in deserialize
Jan 24 12:46:23 cobbler-prv cobblerd[7220]:     raise CX("serializer: error loading collection %s: %s. Check /etc/cobbler/modules.conf"
Jan 24 12:46:23 cobbler-prv cobblerd[7220]: cobbler.cexceptions.CX: "serializer: error loading collection system: <<inherit>> must be one of [<VirtDiskDrivers.INHERTIED: '<<inherit>>'>, <VirtDiskDrivers.RAW: 'raw'>, <VirtDiskDrivers.QCOW2: 'qcow2'>, <VirtDiskDrivers.QED: 'qed'>, <VirtDiskDrivers.VDI: 'vdi'>, <VirtDiskDrivers.VDMK: 'vdmk'>]. Check /etc/cobbler/modules.conf"
````

**Comment by SchoolGuy** [comment]
Argh. We have a test. Why wasn't it triggerd... But thanks for the quick find!
