### ISSUE TITLE
regression in nopxe service

### ISSUE THREAD

**Issue by olafhering** [cobbler/cobbler#2967]
Revision 95443612 does not work properly when a client opens `http://${cobbler-host}/cblr/svc/op/nopxe/system/${system}`

````
[Thu Mar 10 13:01:55.625491 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414] mod_wsgi (pid=1181): Exception occurred processing
 WSGI script '/srv/www/cobbler/svc/services.py'.
[Thu Mar 10 13:01:55.625581 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414] Traceback (most recent call last):
[Thu Mar 10 13:01:55.625606 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/srv/www/cobbler/svc/services.py", line 89
, in application
[Thu Mar 10 13:01:55.625608 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     cw = CobblerSvc(server="http://127.0.0.1:%s" %
 remote_port)
[Thu Mar 10 13:01:55.625613 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib/python3.8/site-packages/cobbler/s
ervices.py", line 51, in __init__
[Thu Mar 10 13:01:55.625615 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     self.api = CobblerAPI()
[Thu Mar 10 13:01:55.625620 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib/python3.8/site-packages/cobbler/a
pi.py", line 90, in __init__
[Thu Mar 10 13:01:55.625622 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     self._settings = self.__generate_settings(path
lib.Path(settingsfile_location),
[Thu Mar 10 13:01:55.625626 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib/python3.8/site-packages/cobbler/a
pi.py", line 156, in __generate_settings
[Thu Mar 10 13:01:55.625628 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     new_settings.save(settings_path)
[Thu Mar 10 13:01:55.625633 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib/python3.8/site-packages/cobbler/s
ettings/__init__.py", line 267, in save
[Thu Mar 10 13:01:55.625635 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     update_settings_file(self.to_dict(), filepath)
[Thu Mar 10 13:01:55.625639 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib/python3.8/site-packages/cobbler/s
ettings/__init__.py", line 356, in update_settings_file
[Thu Mar 10 13:01:55.625641 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     shutil.copy(path, path.parent.joinpath(f"{path
.stem}_{timestamp}{path.suffix}"))
[Thu Mar 10 13:01:55.625650 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib64/python3.8/shutil.py", line 418,
 in copy
[Thu Mar 10 13:01:55.625652 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     copyfile(src, dst, follow_symlinks=follow_syml
inks)
[Thu Mar 10 13:01:55.625656 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]   File "/usr/lib64/python3.8/shutil.py", line 264, in copyfile
[Thu Mar 10 13:01:55.625658 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414]     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
[Thu Mar 10 13:01:55.625668 2022] [wsgi:error] [pid 1181] [client 10.160.67.236:53414] PermissionError: [Errno 13] Permission denied: '/etc/cobbler/settings_20220310_13-01-55.yaml'
````

It is started via `/usr/bin/python3 -s /usr/bin/cobblerd --no-daemonize --config /dev/shm/cobblerd.settings.yaml`

**Comment by olafhering** [comment]
It still works with 1491cf4eb979d1660fb0d74bb43492f3cce6ced8

**Comment by SchoolGuy** [comment]
@olafhering Well if I understood the PR correctly it is expected to not work because ppc is not available officially?

**Comment by olafhering** [comment]
How is `ppc` relevant here?

**Comment by olafhering** [comment]
I did not say this commit is causing it, rather that current master is broken, which happens to be just that commit.

**Comment by SchoolGuy** [comment]
Ah okay. Thanks. Will look into it as soon as time allows.

**Comment by olafhering** [comment]
the breakage is between 1491cf4eb979d1660fb0d74bb43492f3cce6ced8..3eb9e37aba7c19e9c56e7bb128fb1d0929455e8d

**Comment by SchoolGuy** [comment]
Okay. Do you have exact instructions on how to reproduce it?

**Comment by olafhering** [comment]
Try to open the `http=.../nopxe/..` URL, does that work for you?

**Comment by SchoolGuy** [comment]
The root cause of this issue was found in #3016 

For details please see: https://github.com/cobbler/cobbler/issues/3016#issuecomment-1087162768
