### ISSUE TITLE
Cobbler service doesn't start when installed from EPEL

### ISSUE THREAD

**Issue by pmcnabb** [cobbler/cobbler#3088]
### Describe the bug

On a clean installation of Rocky 8, after enabling EPEL repos, enabling the cobbler 3.3 stream, and installing cobbler, the service fails to start. The steps below show the issue in a container, but it is the same error as when running the service through systemd.

### Steps to reproduce

1. podman run -it docker.io/library/rockylinux:8
2. dnf install epel-release 
3. dnf module enable cobbler:3.3
4. /usr/bin/cobblerd -F

### Expected behavior

Expect cobblerd to run.

### Cobbler version

````paste below
cobbler-3.3.2-1.module_el8+14239+adaa624e.noarch
````

### Operating system

Rocky 8.5

### Cobbler log

````paste below
[root@877f700a9809 /]# /usr/bin/cobblerd -F
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 147, in __generate_settings
    normalized_settings = settings.validate_settings(yaml_dict)
  File "/usr/lib/python3.6/site-packages/cobbler/settings/__init__.py", line 280, in validate_settings
    return migrations.normalize(settings_content)
  File "/usr/lib/python3.6/site-packages/cobbler/settings/migrations/__init__.py", line 291, in normalize
    return VERSION_LIST[version].normalize(settings)
  File "/usr/lib/python3.6/site-packages/cobbler/settings/migrations/V3_3_2.py", line 36, in normalize
    return schema.validate(settings)
  File "/usr/lib/python3.6/site-packages/schema.py", line 415, in validate
    raise SchemaWrongKeyError(message, e)
schema.SchemaWrongKeyError: Wrong key 'cache_enabled' in {'auto_migrate_settings': False, 'allow_duplicate_hostnames': False, 'allow_duplicate_ips': False, 'allow_duplicate_macs': False, 'allow_dynamic_settings': False, 'anamon_enabled': False, 'authn_pam_service': 'login', 'auth_token_expiration': 3600, 'autoinstall_snippets_dir': '/var/lib/cobbler/snippets', 'autoinstall_templates_dir': '/var/lib/cobbler/templates', 'boot_loader_conf_template_dir': '/etc/cobbler/boot_loader_conf', 'bootloaders_dir': '/var/lib/cobbler/loaders', 'bootloaders_formats': {'aarch64': {'binary_name': 'grubaa64.efi'}, 'arm': {'binary_name': 'bootarm.efi'}, 'arm64-efi': {'binary_name': 'grubaa64.efi', 'extra_modules': ['efinet']}, 'i386-efi': {'binary_name': 'bootia32.efi'}, 'i386-pc-pxe': {'binary_name': 'grub.0', 'mod_dir': 'i386-pc', 'extra_modules': ['chain', 'pxe', 'biosdisk']}, 'i686': {'binary_name': 'bootia32.efi'}, 'IA64': {'binary_name': 'bootia64.efi'}, 'powerpc-ieee1275': {'binary_name': 'grub.ppc64le', 'extra_modules': ['net', 'ofnet']}, 'x86_64-efi': {'binary_name': 'grubx86.efi', 'extra_modules': ['chain', 'efinet']}}, 'bootloaders_modules': ['btrfs', 'ext2', 'xfs', 'jfs', 'reiserfs', 'all_video', 'boot', 'cat', 'configfile', 'echo', 'fat', 'font', 'gfxmenu', 'gfxterm', 'gzio', 'halt', 'iso9660', 'jpeg', 'linux', 'loadenv', 'minicmd', 'normal', 'part_apple', 'part_gpt', 'part_msdos', 'password_pbkdf2', 'png', 'reboot', 'search', 'search_fs_file', 'search_fs_uuid', 'search_label', 'sleep', 'test', 'true', 'video', 'mdraid09', 'mdraid1x', 'lvm', 'serial', 'regexp', 'tr', 'tftp', 'http', 'luks', 'gcry_rijndael', 'gcry_sha1', 'gcry_sha256'], 'syslinux_dir': '/usr/share/syslinux', 'syslinux_memdisk_folder': '/usr/share/syslinux', 'syslinux_pxelinux_folder': '/usr/share/syslinux', 'grub2_mod_dir': '/usr/lib/grub', 'bootloaders_shim_folder': '/boot/efi/EFI/*/', 'bootloaders_shim_file': 'shim[a-zA-Z0-9]*\\.efi', 'bootloaders_ipxe_folder': '/usr/share/ipxe/', 'build_reporting_enabled': False, 'build_reporting_sender': '', 'build_reporting_email': ['root@localhost'], 'build_reporting_smtp_server': 'localhost', 'build_reporting_subject': '', 'build_reporting_ignorelist': [], 'cheetah_import_whitelist': ['random', 're', 'time', 'netaddr'], 'createrepo_flags': '-c cache -s sha', 'autoinstall': 'default.ks', 'default_name_servers': [], 'default_name_servers_search': [], 'default_ownership': ['admin'], 'default_password_crypted': '$1$mF86/UHC$WvcIcX2t6crBz2onWxyac.', 'default_template_type': 'cheetah', 'default_virt_bridge': 'xenbr0', 'default_virt_file_size': 5, 'default_virt_ram': 512, 'default_virt_type': 'xenpv', 'enable_ipxe': False, 'enable_menu': True, 'http_port': 80, 'kernel_options': {}, 'ldap_server': 'ldap.example.com', 'ldap_base_dn': 'DC=example,DC=com', 'ldap_port': 389, 'ldap_tls': True, 'ldap_anonymous_bind': True, 'ldap_search_bind_dn': '', 'ldap_search_passwd': '', 'ldap_search_prefix': 'uid=', 'ldap_tls_cacertfile': '', 'ldap_tls_keyfile': '', 'ldap_tls_certfile': '', 'ldap_tls_cacertdir': '', 'ldap_tls_cipher_suite': '', 'ldap_tls_reqcert': '', 'mgmt_classes': [], 'mgmt_parameters': {'from_cobbler': True}, 'puppet_auto_setup': False, 'sign_puppet_certs_automatically': False, 'puppetca_path': '/usr/bin/puppet', 'remove_old_puppet_certs_automatically': False, 'puppet_parameterized_classes': True, 'manage_dhcp': False, 'manage_dhcp_v6': False, 'manage_dhcp_v4': False, 'next_server_v4': '127.0.0.1', 'next_server_v6': '::1', 'manage_dns': False, 'bind_chroot_path': '', 'bind_zonefile_path': '/var/named', 'bind_master': '127.0.0.1', 'manage_forward_zones': [], 'manage_reverse_zones': [], 'manage_tftpd': True, 'tftpboot_location': '/var/lib/tftpboot', 'manage_rsync': False, 'power_management_default_type': 'ipmilanplus', 'pxe_just_once': True, 'nopxe_with_triggers': True, 'redhat_management_server': 'xmlrpc.rhn.redhat.com', 'redhat_management_permissive': False, 'redhat_management_key': '', 'register_new_installs': False, 'reposync_flags': '--newest-only --delete --refresh --remote-time', 'reposync_rsync_flags': '-rltDv --copy-unsafe-links', 'restart_dns': True, 'restart_dhcp': True, 'run_install_triggers': True, 'scm_track_enabled': False, 'scm_track_mode': 'git', 'scm_track_author': 'cobbler <cobbler@localhost>', 'scm_push_script': '/bin/true', 'server': '127.0.0.1', 'client_use_localhost': False, 'client_use_https': False, 'virt_auto_boot': True, 'webdir': '/var/www/cobbler', 'webdir_whitelist': ['misc', 'web', 'webui', 'localmirror', 'repo_mirror', 'distro_mirror', 'images', 'links', 'pub', 'repo_profile', 'repo_system', 'svc', 'rendered', '.link_cache'], 'xmlrpc_port': 25151, 'yum_post_install_mirror': True, 'yum_distro_priority': 1, 'yumdownloader_flags': '--resolve', 'serializer_pretty_json': False, 'replicate_rsync_options': '-avzH', 'replicate_repo_rsync_options': '-avzH', 'always_write_dhcp_entries': False, 'proxy_url_ext': '', 'proxy_url_int': '', 'jinja2_includedir': '/var/lib/cobbler/jinja2', 'convert_server_to_ip': False, 'buildisodir': '/var/cache/cobbler/buildiso', 'cobbler_master': '', 'default_virt_disk_driver': 'raw', 'grubconfig_dir': '/var/lib/cobbler/grub_config', 'iso_template_dir': '/etc/cobbler/iso', 'puppet_server': '', 'puppet_version': 2, 'signature_path': '/var/lib/cobbler/distro_signatures.json', 'signature_url': 'https://cobbler.github.io/signatures/3.0.x/latest.json', 'include': ['/etc/cobbler/settings.d/*.settings'], 'cache_enabled': True, 'windows_enabled': False, 'windows_template_dir': '/etc/cobbler/windows', 'samba_distro_share': 'DISTRO', 'nsupdate_enabled': False, 'nsupdate_tsig_algorithm': 'hmac-sha512', 'nsupdate_tsig_key': ['cobbler_update_key.', 'hvnK54HFJXFasHjzjEn09ASIkCOGYSnofRq4ejsiBHz3udVyGiuebFGAswSjKUxNuhmllPrkI0HRSSmM2qvZug=='], 'nsupdate_log': '/var/log/cobbler/nsupdate.log', 'manage_genders': False, 'bind_manage_ipmi': True}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/cobblerd", line 92, in main
    execute_settings_automigration=options.automigration)
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 91, in __init__
    execute_settings_automigration)
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 150, in __generate_settings
    from error
ValueError: Settings are invalid and auto-migration is disabled. Please correct this manually!

````

### Additional information

@opoplawski 

In the RPM's scripts there is a ``grep -q '^cache_enabled:' /etc/cobbler/settings.yaml || echo -e '#ADDED:\ncache_enabled: true' >> /etc/cobbler/settings.yaml``. The presence of this option (cache_enabled) seems to be the cause of the error.

**Comment by opoplawski** [comment]
Update submitted: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-MODULAR-2022-4f52c32316

Probably best to report downstream bugs to bugzilla.redhat.com.

**Comment by SchoolGuy** [comment]
The RPM is now ins table and I consider this bug closed thus.
