### ISSUE TITLE
Cloud-Init Support

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3218]
### Is your feature request related to a problem?

At the moment it is only possible to boot the legacy images of Ubuntu due to the missing cloud-init support.

### Provide a detailed description of the proposed feature

We should have an easy way for users to provision cloud-init. I have no detailed ideas how to approach this except for the bits named below by @heroin-moose.

Cloud-Init further information:

- Website: https://cloud-init.io/
- GH: https://github.com/canonical/cloud-init
- Docs: https://cloudinit.readthedocs.io/en/latest/index.html

### Alternatives you've considered

It is not feasible to not support cloud-init.

### Additional information

This is a dedicated issue that has been split out of:

- https://github.com/cobbler/cobbler/discussions/3217
- https://github.com/cobbler/cobbler/issues/2339

@heroin-moose already proposed a way to support this [here](https://github.com/cobbler/cobbler/issues/2339#issuecomment-994566571)

**Comment by SchoolGuy** [comment]
The important part of the documentation for us are:

- https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#nocloud
- https://cloudinit.readthedocs.io/en/latest/topics/network-config.html

**Comment by SchoolGuy** [comment]
Since I want to get rid of Cheetah long term I will use Jinja templates for this feature. This means validating that #1605 is no longer valid or fix it.

**Comment by SchoolGuy** [comment]
We should be able to make use of the new URL structure in a backwards compatible way with `**rest` parameter that is currently unused. The dict is filled by `__fillup_form_dict`.

---

Credit to @heroin-moose for creating the overview [here](https://github.com/cobbler/cobbler/issues/2339#issuecomment-994778640)

Preseed:

```
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/preseed.cfg
```

Kickstart:

```
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/ks.cfg
```

AutoYAST:

```
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/autoinst.xml
```

cloud-init:

```
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/user-data
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/meta-data
https://cobbler.example.com/cblr/svc/op/autoinstall/system-or-profile/NAME/vendor-data
```

---

Further adjustments need to be done to:

- `AutoinstallManager:generate_autoinstall`: We need to add the filename and the installer type to the method signature.
- `AutoinstallationGen: This should be refactored into per-installer type classes/modules with a base class that aggregates common functionality.
- `AutoinstallManager`: This should be moved under the `AutoinstallGen` module.
- Systems and Profiles need to be able to handle more then one autoinstall template. For this is would be reasonable to do #3267, however since we can do it also without it, we should try to do so.
- We need a data migration that handles that a profile/system can have more then one autoinstall template assigned.
- Moving to multiple templates per distro requires an adjustment in the `signatures.json` format.
- Buildiso Needs to be able to handle this as well.
- We need to extend `cobbler validate-autoinstalls` to work with cloud-init: https://cloudinit.readthedocs.io/en/latest/topics/cli.html#schema

**Comment by SchoolGuy** [comment]
XML-RPC has no concept of kwargs. This makes adding the options as optional arguments really verbose.

Details see here: https://stackoverflow.com/a/120291

**Comment by SchoolGuy** [comment]
@easpeagle You can see that there is a WIP PR linked. In the merge order, this is in the fourth place. Progress is there but not very fast due to atm only me working on all the four PRs.

**Comment by easpeagle** [comment]
@SchoolGuy, I checked out you PR branch to build and test the RPMs. That all built and worked. However, after trying to add and setup ubuntu focal for cloud-init autoinstall, I get this error when trying to start cobblerd now:

Seems like maybe it can't find a validator for cloud-init autoinstall files?

```
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: Traceback (most recent call last):
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/items/item.py", line 897, in from_dict
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     setattr(self, lowered_key, dictionary[key])
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/items/profile.py", line 503, in autoinstall
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     self.api.autoinstall_mgr.validate_autoinstall_template_file_path(
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: AttributeError: 'CobblerAPI' object has no attribute 'autoinstall_mgr'
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: The above exception was the direct cause of the following exception:
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: Traceback (most recent call last):
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 195, in deserialize
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     self.__serializer.deserialize(collection)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/serializer.py", line 115, in deserialize
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     self.storage_object.deserialize(collection, topological)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/modules/serializers/file.py", line 116, in deserialize
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     collection.from_list(datastruct)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 206, in from_list
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     item = self.factory_produce(self.api, item_dict)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/profiles.py", line 33, in factory_produce
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     new_profile.from_dict(item_dict)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/items/profile.py", line 128, in from_dict
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     super().from_dict(dictionary)
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/items/item.py", line 901, in from_dict
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     ) from error
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: AttributeError: Attribute "autoinstall" could not be set!
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: The above exception was the direct cause of the following exception:
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: Traceback (most recent call last):
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/bin/cobblerd", line 111, in main
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     execute_settings_automigration=options.automigration,
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 127, in __init__
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     self.deserialize()
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 2173, in deserialize
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     return self._collection_mgr.deserialize()
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:   File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 200, in deserialize
May 15 20:51:31 gca-cobbler01 cobblerd[33732]:     ) from error
May 15 20:51:31 gca-cobbler01 cobblerd[33732]: cobbler.cexceptions.CX: 'serializer: error loading collection profile: Attribute "autoinstall" could not be set!.Check your settings!'
```

**Comment by SchoolGuy** [comment]
@easpeagle It is very nice to see your interest in the Pull Request. However, it is not in a state where you could test it sadly. The current merge order is:

- https://github.com/cobbler/cobbler/pull/3411
- https://github.com/cobbler/cobbler/pull/2884
- https://github.com/cobbler/cobbler/pull/3295
- https://github.com/cobbler/cobbler/pull/3293

So I will need to rebase the PR multiple times before you will be able to see things working. I will gladly notify you once I am that far if you desire.

**Comment by easpeagle** [comment]
Ah... fair enough, @SchoolGuy ... yeah, I'm more than a little interested. Thanks for continuing to work on this!

**Comment by NileshChandekar** [comment]
[#3573](https://github.com/cobbler/cobbler/discussions/3573)
