### ISSUE TITLE
Problems encountered in installing cobbler 3.3.3 on CentOS7

### ISSUE THREAD

**Issue by zackzhangCN** [cobbler/cobbler#3393]
Hey gays, 
I try to install cobbler 3.3 from source on centos7, but encountered some problems.
It looks like the apache web server is missing, how can I deal with this?

**Version**
Cobbler: 3.3.3
OS: CentOS Linux release 7.9.2009 (Core)
Python: 3.6.8

**Question**
```shell
[root@localhost ~]# systemctl status cobblerd.service
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/etc/systemd/system/cobblerd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

3月 30 09:04:38 localhost.localdomain systemd[1]: Started Cobbler Helper Daemon.
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: ERROR | "getpwnam(): name not found: 'apache'"
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: Traceback (most recent call last):
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: File "/usr/local/bin/cobblerd", line 105, in main
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: app.core(api)
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: File "/usr/local/lib/python3.6/site-packages/cobbler/cobblerd.py", line 48, in core
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: regen_ss_file()
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: File "/usr/local/lib/python3.6/site-packages/cobbler/cobblerd.py", line 70, in regen_ss_file
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: os.lchown("/var/lib/cobbler/web.ss", pwd.getpwnam(http_user)[2], -1)
3月 30 09:04:39 localhost.localdomain cobblerd[8254]: KeyError: "getpwnam(): name not found: 'apache'"
```

Here are my build steps:
```shell
yum -y install epel-release
yum -y install libffi-devel
yum clean all
yum makecache
yum repolist enable
yum update -y

yum install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make
yum install python-pip
pip install wget
wget http://npm.taobao.org/mirrors/python/3.6.8/Python-3.6.8.tar.xz
xz -d Python-3.6.8.tar.xz
tar -xf Python-3.6.8.tar
cd Python-3.6.8
./configure prefix=/usr/local/python3
make && make install
mv /usr/bin/python /usr/bin/python.bak
ln -s /usr/local/python3/bin/python3.6 /usr/bin/python

yum install git
yum install make
yum install wget
yum install curl
yum install createrepo_c
yum install xorriso
yum install python36-gunicorn
yum install python36-cheetah
yum install python36-dns
yum install python36-requests
yum install python36-distro
yum install python36-netaddr
yum install python-librepo
yum install python36-schema
yum install python36-yaml
yum install fence-agents
yum install rsync
yum install syslinux
yum install tftp-server
yum install python36-ldap
yum install python-hivex
yum install python36-pefile
yum install python3-devel
yum install python3-sphinx
yum install python3-coverage
yum install openssl
yum install python36-ldap
yum install rpm-build
yum install python3-future

curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
python get-pip.py

cp /etc/cobbler/cobblerd.service /etc/systemd/system/

Then modify /etc/systemd/system/cobblerd.service, adjust ExecStart from /usr/bin/cobblerd to /usr/local/bin/cobblerd

systemctl daemon-reload
```

**Comment by zackzhangCN** [comment]
After executing python get-pip.py, add cobbler installation steps
```shell
git clone https://github.com/cobbler/cobbler.git
cd cobbler
make install
```

**Comment by zackzhangCN** [comment]
After executing python get-pip.py, add cobbler installation steps
```shell
git clone https://github.com/cobbler/cobbler.git
cd cobbler
make install
```

**Comment by zackzhangCN** [comment]
Thanks, it's such a pity.

**Comment by SchoolGuy** [comment]
Well, the error message you have should be resolvable. What is the user for Apache that would be correct on CentOS7?

**Comment by zackzhangCN** [comment]
Maybe it's apache, i put this question on hold.
I added ExecStartPost=-/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi in cobbled.service
Reinstalled httpd, httpd-devel, python-devel and mod_wsgi
Enter the cobbler decompression directory and execute make webtest
This problem no longer occurs, but a new problem arises:

```shell
[root@localhost tests]# systemctl restart cobblerd
[root@localhost tests]# systemctl status cobblerd
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/etc/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: active (running) since 四 2023-03-30 12:29:39 CST; 5s ago
  Process: 85416 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=1/FAILURE)
 Main PID: 85415 (cobblerd)
   CGroup: /system.slice/cobblerd.service
           └─85415 /usr/bin/python3 /usr/local/bin/cobblerd -F

3月 30 12:29:39 localhost.localdomain systemd[1]: Stopped Cobbler Helper Daemon.
3月 30 12:29:39 localhost.localdomain systemd[1]: Starting Cobbler Helper Daemon...
3月 30 12:29:39 localhost.localdomain touch[85416]: /usr/bin/touch: Error created"/usr/share/cobbler/web/cobbler.wsgi": No such file.
3月 30 12:29:39 localhost.localdomain systemd[1]: Started Cobbler Helper Daemon.
```
But I can't find this file cobbler.wsgi


This is my current progress, I hope it can help you.

**Comment by SchoolGuy** [comment]
`touch` will most likely fail due to a missing directory. Thus you don't even get to the point where Cobbler actually starts. Other than that it could be that `SELinux` is in the way of Cobbler doing certain things.

**Comment by zackzhangCN** [comment]
Yeah, i will try it latter to fix it.
Thanks.
