### ISSUE TITLE
missing template file renders cobblerd unable to start

### ISSUE THREAD

**Issue by lejeczek** [cobbler/cobbler#3526]
### Describe the bug

If not a bug then perhaps a feature-enhancement request - should cobblerd fail
to start for one missing template file?

WARNING | Tried to set the children property on object "" without logical children.
WARNING | Tried to set the children property on object "" without logical children.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cobbler/cobbler_collections/manager.py", line 212, in deserialize
    serializer.deserialize(collection)
  File "/usr/lib/python3.9/site-packages/cobbler/serializer.py", line 128, in deserialize
    storage_module.deserialize(collection, topological)
  File "/usr/lib/python3.9/site-packages/cobbler/modules/serializers/file.py", line 160, in deserialize
    collection.from_list(datastruct)
  File "/usr/lib/python3.9/site-packages/cobbler/cobbler_collections/collection.py", line 201, in from_list
    item = self.factory_produce(self.api, item_dict)
  File "/usr/lib/python3.9/site-packages/cobbler/cobbler_collections/profiles.py", line 45, in factory_produce
    new_profile.from_dict(item_dict)
  File "/usr/lib/python3.9/site-packages/cobbler/items/profile.py", line 136, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.9/site-packages/cobbler/items/item.py", line 890, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.9/site-packages/cobbler/items/profile.py", line 498, in autoinstall
    self._autoinstall = autoinstall_mgr.validate_autoinstall_template_file_path(autoinstall)
  File "/usr/lib/python3.9/site-packages/cobbler/autoinstall_manager.py", line 67, in validate_autoinstall_template_file_path
    raise OSError("Invalid automatic installation template file location %s, file not found" % autoinstall_path)
OSError: Invalid automatic installation template file location /var/lib/cobbler/templates/alma-compiler.ks, file not found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/bin/cobblerd", line 91, in main
    api = cobbler_api.CobblerAPI(is_cobblerd=True, settingsfile_location=options.config,
  File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 105, in __init__
    self.deserialize()
  File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 1797, in deserialize
    return self._collection_mgr.deserialize()
  File "/usr/lib/python3.9/site-packages/cobbler/cobbler_collections/manager.py", line 214, in deserialize
    raise CX("serializer: error loading collection %s: %s. Check /etc/cobbler/modules.conf"
cobbler.cexceptions.CX: 'serializer: error loading collection profile: Invalid automatic installation template file location /var/lib/cobbler/templates/alma-compiler.ks, file not found. Check /etc/cobbler/modules.conf'
cobblerd.service: Main process exited, code=exited, status=1/FAILURE
cobblerd.service: Failed with result 'exit-code'.

### Steps to reproduce

1. create a profile
2. at some point later delete template file
3.

### Cobbler version

````paste below
````
3.3.3
### Operating system
Centos 9

### Cobbler log

````paste below
````

**Comment by SchoolGuy** [comment]
@lejeczek Well what is your wish? In theory, both can be argued for and for now, this is behaviour that is not specifically engineered. I personally don't like stacktraces and as such converting this into a critical log message is the least I would consider to achieve.

**Comment by lejeczek** [comment]
That and similar should not render cobbler so completely dead, not even crippled. Report it, exclaim it, sure, yes, in logs & reports, but do not have cobbler so... delicate, no.
Thanks.
