### ISSUE TITLE
ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>

### ISSUE THREAD

**Issue by zjf199249** [cobbler/cobbler#3556]
### Describe the bug
Using ubuntu to compile cobbler or deb installations also causes errors

### Steps to reproduce

1. `git clone https://github.com/cobbler/cobbler.git`
2. `cd cobbler`
3. `make install`

```
root@kwai:/etc/apache2/conf-enabled# systemctl status cobblerd.service
● cobblerd.service - Cobbler Helper Daemon
     Loaded: loaded (/lib/systemd/system/cobblerd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-01-18 13:51:27 UTC; 57min ago
   Main PID: 4372 (cobblerd)
      Tasks: 1 (limit: 2220)
     Memory: 27.4M
        CPU: 1.173s
     CGroup: /system.slice/cobblerd.service
             └─4372 /usr/bin/python3 -s /usr/bin/cobblerd -F

Jan 18 13:51:27 kwai systemd[1]: Started Cobbler Helper Daemon.
```

```
root@kwai:~# systemctl status apache2
● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-01-19 03:08:42 UTC; 2min 3s ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 6684 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
   Main PID: 6688 (apache2)
      Tasks: 55 (limit: 2220)
     Memory: 5.1M
        CPU: 63ms
     CGroup: /system.slice/apache2.service
             ├─6688 /usr/sbin/apache2 -k start
             ├─6689 /usr/sbin/apache2 -k start
             └─6690 /usr/sbin/apache2 -k start

Jan 19 03:08:42 kwai systemd[1]: Starting The Apache HTTP Server...
Jan 19 03:08:42 kwai apachectl[6687]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Jan 19 03:08:42 kwai systemd[1]: Started The Apache HTTP Server.
```

```
root@kwai:/etc/apache2/conf-enabled# cobbler check
httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cobbler/cli.py", line 864, in check_setup
    s.ping()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
```

### Cobbler version

````paste below
````

### Operating system

```
root@kwai:/etc/apache2/conf-enabled# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

### Cobbler log

````paste below
````

**Comment by SchoolGuy** [comment]
So in our CI this works. Did you reload the Apache configuration so the configuration is getting picked up?

**Comment by zjf199249** [comment]
> 所以在我们的 CI 中，这是有效的。您是否重新加载了 Apache 配置，以便选择配置？
Thank you for your answer. I used this method to solve the problem

ln -s /etc/apache2/conf-available/cobbler.conf /etc/apache2/conf-enabled/
cp /etc/apache2/mods-available/proxy_http.load /etc/apache2/mods-enabled/
cp /etc/apache2/mods-available/proxy.load /etc/apache2/mods-enabled/

**Comment by zjf199249** [comment]
> So in our CI this works. Did you reload the Apache configuration so the configuration is getting picked up?

Thank you for your answer. I used this method to solve the problem

ln -s /etc/apache2/conf-available/cobbler.conf /etc/apache2/conf-enabled/
cp /etc/apache2/mods-available/proxy_http.load /etc/apache2/mods-enabled/
cp /etc/apache2/mods-available/proxy.load /etc/apache2/mods-enabled/

**Comment by SchoolGuy** [comment]
Wonderful that you are getting fuether. On Ubuntu to do this you have the commands:

- `a2enmod`
- `a2ensite`
- `a2enconf`

These are there to help you with managing those configurations. I recommend you to read their manpages.

Is this all or do you have more problems? If not I would kindly ask you to close this issue.
