### ISSUE TITLE
Automigration not possible due to undiscoverable settings

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#3657]
### Describe the bug

I'm trying to update by cobbler install from a git snapshot from 20231126 to the latest 20240308 but cobbler is failing to start.

### Steps to reproduce

1.
2.
3.

### Expected behavior

Cobbler updates settings.

### Cobbler version

Commit bfae8693dcc1cdc85381fc3b6c8a052ee3080bdc

### Operating system

CentOS Stream 9

### Cobbler log

Initially I got:
````paste below
Mar 11 10:32:26 cobblerd[408092]: INFO | Automigration NOT executed
Mar 11 10:32:26 cobblerd[408092]: Traceback (most recent call last):
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 3
27, in __generate_settings
Mar 11 10:32:26 cobblerd[408092]:     normalized_settings = settings.validate_settings(yaml_dict)
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/__init
__.py", line 420, in validate_settings
Mar 11 10:32:26 cobblerd[408092]:     result = migrations.normalize(data)
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/migrat
ions/__init__.py", line 406, in normalize
Mar 11 10:32:26 cobblerd[408092]:     result: Dict[str, Any] = VERSION_LIST[version].normalize(dat
a)
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/migrat
ions/V3_4_0.py", line 203, in normalize
Mar 11 10:32:26 cobblerd[408092]:     return schema.validate(settings)  # type: ignore
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/schema.py", line 426, i
n validate
Mar 11 10:32:26 cobblerd[408092]:     raise SchemaWrongKeyError(message, e.format(data) if e else None)
Mar 11 10:32:26 cobblerd[408092]: schema.SchemaWrongKeyError: Wrong keys 'mgmt_classes', 'mgmt_parameters' in {'auto_migrate_settings': False, 'allow_duplicate_hostnames': False, 'allow_duplicate_ips': False, 'allow_duplicate_macs': False, 'allow_dynamic_settings': False, 'anamon_enabled': False, 'authn_pam_service': 'login', 'auth_token_expiration': 3600, 'autoinstall_snippets_dir': '/var/lib/cobbler/snippets', 'autoinstall_templates_dir': '/var/lib/cobbler/templates', 'boot_loader_conf_template_dir': '/etc/cobbler/boot_loader_conf', 'bootloaders_dir': '/var/lib/cobbler/loaders', 'bootloaders_formats': {'aarch64': {'binary_name': 'grubaa64.efi'}, 'arm': {'binary_name': 'bootarm.efi'}, 'arm64-efi': {'binary_name': 'grubaa64.efi', 'extra_modules': ['efinet']}, 'i386-efi': {'binary_name': 'bootia32.efi'}, 'i386-pc-pxe': {'binary_name': 'grub.0', 'mod_dir': 'i386-pc', 'extra_modules': ['chain', 'pxe', 'biosdisk']}, 'i686': {'binary_name': 'bootia32.efi'}, 'IA64': {'binary_name': 'bootia64.efi'}, 'powerpc-ieee1275': {'binary_name': 'grub.ppc64le', 'extra_modules': ['net', 'ofnet']}, 'x86_64-efi': {'binary_name': 'grubx64.efi', 'extra_modules': ['chain', 'efinet']}}, 'bootloaders_modules': ['btrfs', 'ext2', 'xfs', 'jfs', 'reiserfs', 'all_video', 'boot', 'cat', 'configfile', 'echo', 'fat', 'font', 'gfxmenu', 'gfxterm', 'gzio', 'halt', 'iso9660', 'jpeg', 'linux', 'loadenv', 'minicmd', 'normal', 'part_apple', 'part_gpt', 'part_msdos', 'password_pbkdf2', 'png', 'reboot', 'search', 'search_fs_file', 'search_fs_uuid', 'search_label', 'sleep', 'test', 'true', 'video', 'mdraid09', 'mdraid1x', 'lvm', 'serial', 'regexp', 'tr', 'tftp', 'http', 'luks', 'gcry_rijndael', 'gcry_sha1', 'gcry_sha256'], 'syslinux_dir': '/usr/share/syslinux', 'syslinux_memdisk_folder': '/usr/share/syslinux', 'syslinux_pxelinux_folder': '/usr/share/syslinux', 'grub2_mod_dir': '/usr/lib/grub', 'bootloaders_shim_folder': '/boot/efi/EFI/*/', 'bootloaders_shim_file': 'shim[a-zA-Z0-9]*\\.efi', 'bootloaders_ipxe_folder': '/usr/share/ipxe/', 'build_reporting_enabled': False, 'build_reporting_sender': '', 'build_reporting_email': ['root@localhost'], 'build_reporting_smtp_server': 'localhost', 'build_reporting_subject': '', 'build_reporting_ignorelist': [], 'cheetah_import_whitelist': ['random', 're', 'time', 'netaddr'], 'createrepo_flags': '--cachedir=cache --update', 'autoinstall': 'default.ks', 'default_name_servers': [], 'default_name_servers_search': [], 'default_ownership': ['admin'], 'default_password_crypted': '$1$mF86/UHC$WvcIcX2t6crBz2onWxyac.', 'default_template_type': 'cheetah', 'default_virt_bridge': 'virbr0', 'default_virt_file_size': 5.0, 'default_virt_ram': 512, 'default_virt_type': 'kvm', 'enable_ipxe': False, 'enable_menu': True, 'http_port': 80, 'kernel_options': {}, 'ldap_server': 'ldap.example.com', 'ldap_base_dn': 'DC=example,DC=com', 'ldap_port': 389, 'ldap_tls': True, 'ldap_anonymous_bind': True, 'ldap_search_bind_dn': '', 'ldap_search_passwd': '', 'ldap_search_prefix': 'uid=', 'ldap_tls_cacertfile': '', 'ldap_tls_keyfile': '', 'ldap_tls_certfile': '', 'ldap_tls_cacertdir': '', 'ldap_tls_cipher_suite': '', 'ldap_tls_reqcert': '', 'mgmt_classes': [], 'mgmt_parameters': {'from_cobbler': True}, 'puppet_auto_setup': False, 'sign_puppet_certs_automatically': False, 'puppetca_path': '/usr/bin/puppet', 'remove_old_puppet_certs_automatically': False, 'puppet_parameterized_classes': True, 'manage_dhcp': True, 'manage_dhcp_v6': False, 'manage_dhcp_v4': True, 'next_server_v4': '127.0.0.1', 'next_server_v6': '::1', 'manage_dns': False, 'bind_chroot_path': '', 'bind_manage_ipmi': True, 'bind_zonefile_path': '/var/named', 'bind_master': '127.0.0.1', 'manage_forward_zones': [], 'manage_reverse_zones': [], 'manage_genders': False, 'manage_tftpd': True, 'tftpboot_location': '/var/lib/tftpboot', 'manage_rsync': False, 'power_management_default_type': 'ipmilanplus', 'pxe_just_once': True, 'nopxe_with_triggers': True, 'redhat_management_server': 'xmlrpc.rhn.redhat.com', 'redhat_management_permissive': False, 'redhat_management_key': '', 'register_new_installs': False, 'reposync_flags': '--newest-only --delete --refresh --remote-time', 'reposync_rsync_flags': '-rltDv --copy-unsafe-links', 'restart_dns': True, 'restart_dhcp': True, 'run_install_triggers': True, 'scm_track_enabled': False, 'scm_track_mode': 'git', 'scm_track_author': 'cobbler <cobbler@localhost>', 'scm_push_script': '/bin/true', 'server': '127.0.0.1', 'client_use_localhost': False, 'client_use_https': False, 'virt_auto_boot': True, 'webdir': '/var/www/cobbler', 'webdir_whitelist': ['misc', 'web', 'webui', 'localmirror', 'repo_mirror', 'distro_mirror', 'images', 'links', 'pub', 'repo_profile', 'repo_system', 'svc', 'rendered', '.link_cache'], 'xmlrpc_port': 25151, 'yum_post_install_mirror': True, 'yum_distro_priority': 1, 'yumdownloader_flags': '--resolve', 'serializer_pretty_json': False, 'replicate_rsync_options': '-avzH', 'replicate_repo_rsync_options': '-avzH', 'always_write_dhcp_entries': False, 'proxy_url_ext': '', 'proxy_url_int': '', 'jinja2_includedir': '/var/lib/cobbler/jinja2', 'convert_server_to_ip': False, 'buildisodir': '/var/cache/cobbler/buildiso', 'cobbler_master': '', 'default_virt_disk_driver': 'raw', 'grubconfig_dir': '/var/lib/cobbler/grub_config', 'iso_template_dir': '/etc/cobbler/iso', 'puppet_server': '', 'puppet_version': 2, 'signature_path': '/var/lib/cobbler/distro_signatures.json', 'signature_url': 'https://cobbler.github.io/signatures/3.0.x/latest.json', 'nsupdate_enabled': False, 'nsupdate_tsig_algorithm': 'hmac-sha512', 'nsupdate_tsig_key': ['cobbler_update_key.', 'hvnK54HFJXFasHjzjEn09ASIkCOGYSnofRq4ejsiBHz3udVyGiuebFGAswSjKUxNuhmllPrkI0HRSSmM2qvZug=='], 'nsupdate_log': '/var/log/cobbler/nsupdate.log', 'windows_enabled': False, 'windows_template_dir': '/etc/cobbler/windows', 'samba_distro_share': 'DISTRO', 'modules': {'authentication': {'module': 'authentication.configfile', 'hash_algorithm': 'sha3_512'}, 'authorization': {'module': 'authorization.allowall'}, 'dns': {'module': 'managers.bind'}, 'dhcp': {'module': 'managers.dnsmasq'}, 'tftpd': {'module': 'managers.in_tftpd'}, 'serializers': {'module': 'serializers.file'}}, 'mongodb': {'host': 'localhost', 'port': 27017}, 'cache_enabled': False, 'autoinstall_scheme': 'http', 'lazy_start': False}
Mar 11 10:32:26 cobblerd[408092]: The above exception was the direct cause of the following exception:
Mar 11 10:32:26 cobblerd[408092]: Traceback (most recent call last):
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/bin/cobblerd", line 108, in main
Mar 11 10:32:26 cobblerd[408092]:     api = cobbler_api.CobblerAPI(
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 235, in __init__
Mar 11 10:32:26 cobblerd[408092]:     self._settings = self.__generate_settings(
Mar 11 10:32:26 cobblerd[408092]:   File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 329, in __generate_settings
Mar 11 10:32:26 cobblerd[408092]:     raise ValueError(
Mar 11 10:32:26 cobblerd[408092]: ValueError: Settings are invalid and auto-migration is disabled. Please correct this manually!
````
After enabling auto migration:
```
Mar 11 10:34:10 cobblerd[408838]: INFO | Automigration executed
Mar 11 10:34:10 cobblerd[408838]: Traceback (most recent call last):
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/bin/cobblerd", line 108, in main
Mar 11 10:34:10 cobblerd[408838]:     api = cobbler_api.CobblerAPI(
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 235, in __init__
Mar 11 10:34:10 cobblerd[408838]:     self._settings = self.__generate_settings(
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 322, in __generate_settings
Mar 11 10:34:10 cobblerd[408838]:     normalized_settings = settings.migrate(yaml_dict, settings_path)
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/__init__.py", line 580, in migrate
Mar 11 10:34:10 cobblerd[408838]:     result = migrations.migrate(data, settings_path)
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/migrations/__init__.py", line 326, in migrate
Mar 11 10:34:10 cobblerd[408838]:     return auto_migrate(yaml_dict, settings_path, ignore_keys)
Mar 11 10:34:10 cobblerd[408838]:   File "/usr/lib/python3.9/site-packages/cobbler/settings/migrations/__init__.py", line 285, in auto_migrate
Mar 11 10:34:10 cobblerd[408838]:     raise RuntimeError("Automigration not possible due to undiscoverable settings!")
Mar 11 10:34:10 cobblerd[408838]: RuntimeError: Automigration not possible due to undiscoverable settings!
```

**Comment by opoplawski** [comment]
After commenting out the mgmt settings:
```
Mar 11 10:51:35 cobblerd[411526]: ERROR | Error while loading a collection: "The following keys supplied could not be set: dict_keys(['mgmt_parameters'])". Skipping collection distro!
Mar 11 10:51:35 cobblerd[411526]: ERROR | Error while loading a collection: "The following keys supplied could not be set: dict_keys(['mgmt_classes', 'mgmt_parameters'])". Skipping collection repo!
Mar 11 10:51:35 cobblerd[411526]: ERROR | Error while loading a collection: distribution "centos-stream-9-x86_64" not found. Skipping collection profile!
```
It seems like a lot more migration work is going to be needed.
