### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#3826]
### Describe the bug

cobblerd fails to run with Python 3.13 which is in the soon to be released Fedora 41.  At least one issue:

```
Sep 23 16:50:02 python3[12385]: detected unhandled Python exception in '/usr/bin/cobblerd'
Sep 23 16:50:02 cobblerd[12385]: Traceback (most recent call last):
Sep 23 16:50:02 cobblerd[12385]:   File "/usr/bin/cobblerd", line 21, in <module>
Sep 23 16:50:02 cobblerd[12385]:     import cobbler.cobblerd as app
Sep 23 16:50:02 cobblerd[12385]:   File "/usr/lib/python3.13/site-packages/cobbler/cobblerd.py", line 29, in <module>
Sep 23 16:50:02 cobblerd[12385]:     from cobbler.api import CobblerAPI
Sep 23 16:50:02 cobblerd[12385]:   File "/usr/lib/python3.13/site-packages/cobbler/api.py", line 34, in <module>
Sep 23 16:50:02 cobblerd[12385]:     from cobbler.actions import status, hardlink, sync, replicate, report, log, acl, check, reposync, mkloaders
Sep 23 16:50:02 cobblerd[12385]:   File "/usr/lib/python3.13/site-packages/cobbler/actions/reposync.py", line 26, in <module>
Sep 23 16:50:02 cobblerd[12385]:     import pipes
Sep 23 16:50:02 cobblerd[12385]: ModuleNotFoundError: No module named 'pipes'
```
### Steps to reproduce

1. Build/install cobbler on Fedora 41
2. Try to start cobblerd

### Expected behavior
Cobbler runs.
### Cobbler version

````paste below
3.3.6
````

### Operating system

Fedora 41

**Comment by Ionys320** [comment]
Cheetah is also using `cgi`, who has been deprecated in Python 3.13.

**Comment by SchoolGuy** [comment]
There were plans in my head to move towards Jinja 2 as the default template engine. It seems we need to speed up these plans rather soon.
