### ISSUE TITLE
ModuleNotFoundError: No module named 'cobbler.wsgi' when starting cobblerd-gunicorn.service from source installation

### ISSUE THREAD

**Issue by helloxjade** [cobbler/cobbler#3844]
### Describe the bug

I am encountering a `ModuleNotFoundError: No module named 'cobbler.wsgi'` when attempting to start the `cobblerd-gunicorn.service` after installing Cobbler 3.3.6 from source. The error suggests that the `cobbler.wsgi` module cannot be found, preventing the Gunicorn service from starting.

### Steps to reproduce

1. ubuntu22.04
2.Installed Cobbler 3.3.6 from source via the instructions provided in the official documentation
3.Attempted to start the `cobblerd-gunicorn.service`.

### Expected behavior

The service should start without any issues

### Cobbler version

````
cobbler version
httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cobbler/cli.py", line 867, in check_setup
    s.ping()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
````

### Operating system

ubuntu22.04

### Cobbler log

````
cat /var/log/cobbler/cobbler.log
[Daemon] 2024-11-12T05:37:27 - INFO | Automigration NOT executed
[Daemon] 2024-11-12T05:37:27 - INFO | python3-hivex not found. If you need Automatic Windows Installation support, please install.
[Daemon] 2024-11-12T05:37:28 - INFO | 11 breeds and 146 OS versions read from the signature file
[Daemon] 2024-11-12T05:37:28 - INFO | Cobbler startup completed 
[Daemon] 2024-11-12T15:22:22 - INFO | Automigration NOT executed
[Daemon] 2024-11-12T15:22:23 - INFO | python3-hivex not found. If you need Automatic Windows Installation support, please install.
[Daemon] 2024-11-12T15:22:23 - INFO | 11 breeds and 146 OS versions read from the signature file
[Daemon] 2024-11-12T15:22:23 - INFO | Cobbler startup completed 
[Daemon] 2024-11-12T15:25:17 - INFO | Automigration NOT executed
[Daemon] 2024-11-12T15:25:17 - INFO | python3-hivex not found. If you need Automatic Windows Installation support, please install.
[Daemon] 2024-11-12T15:25:17 - INFO | 11 breeds and 146 OS versions read from the signature file
[Daemon] 2024-11-12T15:25:18 - INFO | Cobbler startup completed 
[Daemon] 2024-11-13T03:02:57 - INFO | running: ['/usr/sbin/selinuxenabled']
[Daemon] 2024-11-13T03:02:57 - INFO | received on stdout: 
[Daemon] 2024-11-13T03:02:57 - INFO | Automigration NOT executed
[Daemon] 2024-11-13T03:02:58 - INFO | python3-hivex not found. If you need Automatic Windows Installation support, please install.
[Daemon] 2024-11-13T03:02:58 - INFO | 11 breeds and 146 OS versions read from the signature file
[Daemon] 2024-11-13T03:02:58 - INFO | Cobbler startup completed 
````

````
 journalctl -u cobblerd-gunicorn.service
 
 ]: Failed to start Cobblerd Gunicorn Service.
Nov 13 02:19:07 root systemd[1]: Started Cobblerd Gunicorn Service.
Nov 13 02:19:07 root gunicorn[35571]: [2024-11-13 02:19:07 +0000] [35571] [INFO] Starting gunicorn 20.1.0
Nov 13 02:19:07 root gunicorn[35571]: [2024-11-13 02:19:07 +0000] [35571] [INFO] Listening at: http://0.0.0.0:8000 (35571)
Nov 13 02:19:07 root gunicorn[35571]: [2024-11-13 02:19:07 +0000] [35571] [INFO] Using worker: sync
Nov 13 02:19:07 root gunicorn[35572]: [2024-11-13 02:19:07 +0000] [35572] [INFO] Booting worker with pid: 35572
Nov 13 02:19:07 root gunicorn[35572]: [2024-11-13 02:19:07 +0000] [35572] [ERROR] Exception in worker process
Nov 13 02:19:07 root gunicorn[35572]: Traceback (most recent call last):
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Nov 13 02:19:07 root gunicorn[35572]:     worker.init_process()
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
Nov 13 02:19:07 root gunicorn[35572]:     self.load_wsgi()
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Nov 13 02:19:07 root gunicorn[35572]:     self.wsgi = self.app.wsgi()
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
Nov 13 02:19:07 root gunicorn[35572]:     self.callable = self.load()
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
Nov 13 02:19:07 root gunicorn[35572]:     return self.load_wsgiapp()
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Nov 13 02:19:07 root gunicorn[35572]:     return util.import_app(self.app_uri)
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
Nov 13 02:19:07 root gunicorn[35572]:     mod = importlib.import_module(module)
Nov 13 02:19:07 root gunicorn[35572]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Nov 13 02:19:07 root gunicorn[35572]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 13 02:19:07 root gunicorn[35572]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Nov 13 02:19:07 root gunicorn[35572]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Nov 13 02:19:07 root gunicorn[35572]:   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
Nov 13 02:19:07 root gunicorn[35572]: ModuleNotFoundError: No module named 'cobbler.wsgi'
````

### Screenshots

python3 --version
Python 3.10.12

**Comment by SchoolGuy** [comment]
@helloxjade Hey there! Cobbler 3.3.6 doesn't use gunicorn. I believe that you are mixing up the main development branch and 3.3.6 in some matter. I am still willing to provide assistance with your issue but this bug sounds very much invalid with the currently given information.
