### ISSUE TITLE
Upload to PyPi wasn't successful for 3.2.3 tag

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#3856]
### Describe the bug

See title

### Steps to reproduce

1. See title

### Expected behavior

Upload succeeds.

### Cobbler version

````paste below
3.2.3
````

### Operating system

Ubuntu 22.04 LTS

### Cobbler log

````paste below
Processing /home/runner/work/cobbler/cobbler
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/runner/work/cobbler/cobbler/setup.py", line 18, in <module>
          from sphinx.setup_command import BuildDoc
      ModuleNotFoundError: No module named 'sphinx.setup_command'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

### Screenshots

None

### Additional information

None

**Comment by SchoolGuy** [comment]
Tag is available in PyPi, PR is merged. Closing issue.
